### ISSUE TITLE
一个设备token对应多个token就好了，这样就能告诉别人token了。

### ISSUE THREAD

**Issue by tomzcn** [Finb/Bark#10]
一个设备token对应多个token就好了，这样就能告诉别人token了。

**Comment by wahao** [comment]
小程序助手  已经支持生成临时链接        可以随时禁用、删除临时链接    可以随心分享链接给别人喽

入口： 我的 > 实验性功能 > 临时链接 

[Bark-MP-helper](https://github.com/wahao/Bark-MP-helper)


![](https://mmbiz.qpic.cn/mmbiz_jpg/icWtmsIaSA69CyHTsibIXzplqso95e8IknUAnEC4JAYX8STEVrZAPCTBLeMjibuvu23XJsa1WicKaeEOh5GPlY5RUQ/0?wx_fmt=jpeg)



![演示](https://github.com/wahao/Bark-MP-helper/blob/master/images/WechatIMG1136.jpeg)
