### ISSUE TITLE
添加多个私人服务器问题

### ISSUE THREAD

**Issue by info-CH** [Finb/Bark#101]
添加第二个服务器地址会覆盖第一次添加的地址 并且能接收到两个服务器地址的推送不知道算不算bug
并且没办法复制第一次添加的服务器地址。默认显示第二次添加的
然后重新添加地址后也没弹窗 但是两个服务器推送内容都可以收到不影响

**Comment by info-CH** [comment]
可能讲的有点乱 大概就就像
我添加了a地址正常主页面显示的是a地址
然后我又添加了b地址.主页会替换掉a地址成为b的地址
添加的a/b地址都能正常收到推送消息 但是不能在看到a地址了默认显示b地址
所以这算不算一个小bug。
比如我想添加多个服务器地址 但是没有编辑服务器地址的地方

**Comment by Finb** [comment]
确实是这样
添加服务器其实是将自己的推送 deviceToken 发送到服务器，服务器保存后用这个token将推送消息发给苹果。
添加第二个服务器并不会删除第一个服务器保存的 deviceToken，所以两个服务器都能推。

deviceToken 失效后第一个服务器就不能推了
第二个服务器会持续收到APP发来的最新的 deviceToken 保持正常推送。
不过一般 deviceToken 也不怎么会失效。

**Comment by info-CH** [comment]
> 确实是这样
> 添加服务器其实是将自己的推送 deviceToken 发送到服务器，服务器保存后用这个token将推送消息发给苹果。
> 添加第二个服务器并不会删除第一个服务器保存的 deviceToken，所以两个服务器都能推。
> 
> deviceToken 失效后第一个服务器就不能推了
> 第二个服务器会持续收到APP发来的最新的 deviceToken 保持正常推送。
> 不过一般 deviceToken 也不怎么会失效。

所以就等于只是暂时没有服务器管理的地方了。
其他真不错。
