### ISSUE TITLE
Feature request: iOS 端通知消息分组

### ISSUE THREAD

**Issue by lytning98** [Finb/Bark#105]
如图，QQ/微信等 app 的通知在通知中心显示时有分组功能，来自不同联系人的消息会分组折叠在一起。Bark 目前已经有一些分组功能了，希望在推送通知时也能实现这样的分组推送功能，方便分类浏览通知。

![image](https://user-images.githubusercontent.com/23375707/128585161-26399958-e55e-451d-ba8f-f230759ff1bd.png)

**Comment by Finb** [comment]
感谢建议，马上支持上。
这是一个我之前不知道的特性，看了下文档这特性挺有用的

lytning98 ***@***.***>于2021年8月7日 周六10:36写道：

**Comment by Finb** [comment]
已经上线了，你试试~

**Comment by lytning98** [comment]
> 已经上线了，你试试~

发现了，非常感谢！太高效了~
