### ISSUE TITLE
添加小组件功能

### ISSUE THREAD

**Issue by xuanyanwow** [Finb/Bark#112]
对于小组件功能的自定义显示，是否有可行性，比如做一个行程提示的功能，除了推送消息外，还可以在小组件中显示今日行程等数据

**Comment by Finb** [comment]
听起来挺有意思，延伸一下，可以推送任意文字到小组件上。

但我不清楚现在小组件是否能支持这种功能。
小组件是提前设好更新计划托管给系统的，很难用推送去实时更新，我得先研究研究

**Comment by xuanyanwow** [comment]
感谢回复。我是一名PHP程序员，所以IOS前端这一块不太懂，劳烦您费心了。
按照其他软件的模式，软件内置了N种小组件模板  可以供用户选择。（主要看官方对于小组件模板的审核麻烦程度怎么样）
另外关于数据，有两种模式，应该是按第一种才比较合理。
1. 在软件中配置API地址（直接读取用户服务器的数据） 需要提供开发文档说明数据
2. 用户推送给咱官网服务器，做一个数据缓存（不然的话就需要用户一直Push 才会实时更新数据），对咱官网服务器压力较大
