### ISSUE TITLE
手机迁移后新手机没有收到推送

### ISSUE THREAD

**Issue by aotian16** [Finb/Bark#114]
买了新手机后，迁移数据到新手机上了，老的iphone还能收到推送，新的iphone没有收到，需要什么设置吗？还是说卸载老iphone上的客户端就可以了？

**Comment by Finb** [comment]
这块确实有点问题，
如果迁移的话，新旧设备用的同一个key ，但新旧设备的 deviceToken 各自不一样，
推送应该会推到最后一个打开了 APP 的设备上。

你先暂时 新旧设备选一个卸载重装一下，重置一下key吧

**Comment by aotian16** [comment]
好的，谢谢

**Comment by Finb** [comment]
1.2.7 版本新增重置key功能，可以在新手机重置一下key解决。
