### ISSUE TITLE
push操作的时候怎么对消息进行分组

### ISSUE THREAD

**Issue by machangxin** [Finb/Bark#117]
push操作的时候，我发现category没有用，还是放在了默认群组里面

**Comment by Finb** [comment]
可以查看应用内教程卡片，上面有写是通过携带 groupName 参数来分组的，并有url一个示例

**Comment by machangxin** [comment]
抱歉，写错了，是post请求

**Comment by Finb** [comment]
post请求参数名是一样的，用group就可以，参数值就是分组名
