### ISSUE TITLE
提供 iPad 适配

### ISSUE THREAD

**Issue by cheer-cheer** [Finb/Bark#118]
目前的版本虽然可以在 iPad 上打开，但是没有适配，界面很难看，可否为 iPad 添加适配？

**Comment by mrbillxp** [comment]
Yes. I am looking forward for that app optimize for the big screen iPad.

**Comment by Finb** [comment]
已适配，可以 TestFlight 下载试用。
https://testflight.apple.com/join/7rA2TUok
