### ISSUE TITLE
希望可以增加一个自动打开URL的功能

### ISSUE THREAD

**Issue by xqin** [Finb/Bark#128]
目前有 `automaticallyCopy` 参数, 在收到推送的时候, 自动复制推送的内容.

希望可以增加一个 `automaticallyOpen` 这样的参数(结合`url`参数), 支持在收到推送的 URL 时, 在不点击通知的情况下, 自动打开该 URL 地址.

场景是: 目前我通过 向手机端推送 另一个App的URL 实现在收到通知时, 打开另一个App.

但目前的情况是: 
1. 点击收到的通知.
2. 会自动切换到 Bark App.
3. Bark App 打开收到的URL地址.
4. URL 触发启动一个App.

希望的结果是, 在传入 `automaticallyOpen=1` 时, Bark 可以自动打开对应的URL(触发切换到另一个App).

这样 1 不用再点通知, 2 不会再切换到Bark, 然后再切换到另一个App.

示例场景:

```
https://example.com/${deviceId}/title?automaticallyOpen=1&url=weixin%3A%2F%2Faaa%3Fxx%3D1%26yy%3D2
```

谢谢 :)

**Comment by Finb** [comment]
应该做不到这样的交互，iOS没有权限允许这样做
