### ISSUE TITLE
post请求体中group参数无效

### ISSUE THREAD

**Issue by leafney** [Finb/Bark#129]
post方式请求，在请求体中添加 `group` 参数后发现接收到的消息保存在 `默认` 分组中。
```
{
    "title":"测试",
    "body":"这是内容",
    "group":"test"   
}
```

如果是添加在URL中 `/yourkey?group=test` 这样是可以的，新增了 `test` 分组。

App版本信息： Github Run Id : 1389319857

**Comment by Finb** [comment]
使用 v2 接口请参考
https://github.com/Finb/bark-server/blob/master/docs/API_V2.md

group 需要放在 ext_params 节点下

**Comment by leafney** [comment]
Thanks
