### ISSUE TITLE
我替你的BARK写了个PC端辅助软件，有需要的话拿去用吧

### ISSUE THREAD

**Issue by HsuDan** [Finb/Bark#13]
你的BARK非常棒，很符合我的需求，唯独在PC上使用比较繁琐，所以我用上古时期的DELPHI（我只会Pascal，哈哈）写了个辅助软件BarkHelper，有需要的话就拿去用吧，我也放在Github上开源了。

https://github.com/HsuDan/BarkHelper

**Comment by romebake** [comment]
我也写了个PC小工具，主要用于快捷键自动推送剪切板内容，有兴趣的可以尝试下😄
https://github.com/romebake/AutoBark4Windows

**Comment by kaixinsoft** [comment]
> 你的BARK非常棒，很符合我的需求，唯独在PC上使用比较繁琐，所以我用上古时期的DELPHI（我只会Pascal，哈哈）写了个辅助软件BarkHelper，有需要的话就拿去用吧，我也放在Github上开源了。
> 
> https://github.com/HsuDan/BarkHelper

Delphi现在可以做iOS和android的app，可以做mac系统的应用程序，windows下的更不用说了，功能很强大

**Comment by HsuDan** [comment]
> > 你的BARK非常棒，很符合我的需求，唯独在PC上使用比较繁琐，所以我用上古时期的DELPHI（我只会Pascal，哈哈）写了个辅助软件BarkHelper，有需要的话就拿去用吧，我也放在Github上开源了。
> > https://github.com/HsuDan/BarkHelper
> 
> Delphi现在可以做iOS和android的app，可以做mac系统的应用程序，windows下的更不用说了，功能很强大

哈哈，这样啊，我还以为Delphi已经过时了，“Delphi盒子”上面更新时间都是好多年前了，显示最新的只有Delphi 7
