### ISSUE TITLE
使用https不能用

### ISSUE THREAD

**Issue by 21100756** [Finb/Bark#131]
你好，我是再宝塔上面搭建的服务端，然后开了个域名并且申请了ssl  使用域名进行http访问没有问题，https不能访问，请问还需要配置什么吗？

**Comment by Finb** [comment]
还需要配置SSL呀，申请了不是直接就能用。
我并没有用过宝塔，所以我建议你搜索 宝塔配置SSL 找相关教程。
另外你可以先在浏览器上访问，看看浏览器的报错，再根据报错搜索相关教程。
