### ISSUE TITLE
用换行有问题，请教

### ISSUE THREAD

**Issue by eryuehua-jian** [Finb/Bark#132]
https://api.day.app/key/今日新闻/国家安全'\n'教育课时

上面是链接，下面是通知结果

**国家安全'**
  n'教育课时

换行符用起来感觉有问题啊
正常来说只是用了换行符 为什么标题不显示了，而且换行符号也有问题。。。

**Comment by xilou31** [comment]
需要对换行这种特殊字符进行编码再发送

**Comment by eryuehua-jian** [comment]
对整个body一起编码行不行> 需要对换行这种特殊字符进行编码再发送

**Comment by xilou31** [comment]
也可以呀，但是你要自己手动解码不也挺麻烦的

**Comment by stilleshan** [comment]
https://api.day.app/key/今日新闻/国家安全%0a教育课时

**Comment by eryuehua-jian** [comment]
> https://api.day.app/key/今日新闻/国家安全%0a教育课时

你这个用起来方便

**Comment by stilleshan** [comment]
> > [https://api.day.app/key/今日新闻/国家安全%0a教育课时](https://api.day.app/key/%E4%BB%8A%E6%97%A5%E6%96%B0%E9%97%BB/%E5%9B%BD%E5%AE%B6%E5%AE%89%E5%85%A8%0a%E6%95%99%E8%82%B2%E8%AF%BE%E6%97%B6)
> 
> 你这个用起来方便

可以就 close issue
