### ISSUE TITLE
带中文的 URL 推送，点击不能跳转

### ISSUE THREAD

**Issue by ryanlid** [Finb/Bark#137]
例如：
```
curl 'https://api.day.app/{KEY}/' \
  -H 'content-type: application/json' \
  -d '{"title":"创建笔记","body":"内容","group":"test","url":"https://www.baidu.com/s?wd=中文"}'
```
推送后，点击推送消息，不能跳转打开 URL地址

![图片](https://user-images.githubusercontent.com/6867964/154196996-41d87312-5ac8-4a75-ab74-aded4ae847be.jpg)

**Comment by Finb** [comment]
URL规范中不允许出现中文, 常见的浏览器上显示出中文都是浏览器做了一个转换，实际复制下来的真实URL是如下面这样的。
https://www.baidu.com/s?wd=%E4%B8%AD%E6%96%87 ，传递也应该传这样的

简单点处理，就是URL中的参数部分如果出现特殊字符，则加一层URL编码（最好无脑加一层）
https://www.baidu.com/s?wd={url编码后的参数值}
