### ISSUE TITLE
长文本(>1W字)推送能否实现？

### ISSUE THREAD

**Issue by popsee** [Finb/Bark#139]
bark试了好几次，用post也无法实现长文本(大于1W汉字)的内容推送，短消息推送均早已接入bark，但就差长文本消息推送，无法接入，比如有需求多账号的消息反馈推送，文字总和一起就于1W汉字了，但可能超过iOS推送的字符数限制（据说是[1K字](https://blog.csdn.net/danny35/article/details/45041005/)左右），如果换成单账户消息连续推送又不太友好（连续叮叮推送声音），且阅读一个一个点击也麻烦。
目前在用微信企业超文本推送，但感觉也不太友好，每次查询都需要点击好几次才能进入阅读界面，没有bark这么清爽直接进入消息内容。
希望大神能够给个好的解决方案，谢谢！

**Comment by popsee** [comment]
已在完美解决，完全支持长文本的发送，在App Store挨个试的，OK，搞定！

**Comment by lovedancer075** [comment]
请问怎么搞定的？这个貌似是GET请求的限制吧？
