### ISSUE TITLE
使用curl 访问推送链接的时候，ios收到的中文通知是乱码

### ISSUE THREAD

**Issue by tozehu** [Finb/Bark#14]
在windows下使用“curl https://host/key/哈哈哈” 命令 手机收到的推送是乱码，麻烦指导一下怎么处理？

**Comment by Finb** [comment]
我身边没有windows电脑不好判断问题所在，
我猜应该是编码问题
你可以搜一下 windows curl 中文乱码 尝试解决一下

另外你可以把URL在Chrome浏览器中请求一下，看是否正常，对比下看问题是不是出在curl上

**Comment by tozehu** [comment]
好的，谢谢
