### ISSUE TITLE
请问可以支持消息跳转到指定的app吗？

### ISSUE THREAD

**Issue by mengzhongshuike** [Finb/Bark#143]

**Comment by Finb** [comment]
可以的，前提是对应APP有 url scheme 或 universal link

**Comment by wangzai9527** [comment]
> 可以的，前提是对应APP有 url scheme 或 universal link

你好请问下这个怎么实现？  有对应的url scheme

**Comment by Finb** [comment]
> > 可以的，前提是对应APP有 url scheme 或 universal link
> 
> 你好请问下这个怎么实现？ 有对应的url scheme

使用 url 参数

**Comment by wangzai9527** [comment]
> > > 可以的，前提是对应APP有 url scheme 或 universal link
> 
> > 
> 
> > 你好请问下这个怎么实现？ 有对应的url scheme
> 
> 
> 
> 使用 url 参数

好的谢谢，搞定了

**Comment by jibill** [comment]
我也有个问题：打开京东App是正常的：url=openApp.jdMobile://
但是打开快捷指令有问题： url=shortcuts://run-shortcut?name=测试快捷&input=text&text=xxxx
![image](https://user-images.githubusercontent.com/42427328/201998594-c8fd10d9-76cd-4179-9209-ba9f95ec305d.png)
