### ISSUE TITLE
现在我的手机是ios15以上，但是使用icon参数失效了，请问是怎么回事

### ISSUE THREAD

**Issue by silk-java** [Finb/Bark#145]
现在我的手机是ios15以上，但是使用icon参数失效了，请问是怎么回事

**Comment by Finb** [comment]
icon 要能正常访问，必须是图片url

如果参数都正确设置还没没有，可以重启下手机试试

**Comment by silk-java** [comment]
多谢回复，目前我访问的地址是https://7383-122-193-105-243.ngrok.io/此处是我的devicekey/hispring?icon=https://tui.juhe.cn/img/pc-logo.e6317822.svg，手机重启了，也还是不行，以前测试还可以的

**Comment by silk-java** [comment]
https://7383-122-193-105-243.ngrok.io/此处是deveice_key/hispring?icon=https://tui.juhe.cn/img/pc-logo.e6317822.svg

**Comment by Finb** [comment]
svg 矢量图暂时不行，必须使用位图例如 jpg png

**Comment by silk-java** [comment]
非常感谢回复，已经测试成功
