### ISSUE TITLE
heroku部署以后URL模式访问能正常发送消息及提醒，但是在Bark App中服务器添加就出现“填写的服务器无效，请重试！网络错误”

### ISSUE THREAD

**Issue by neohob** [Finb/Bark#150]
heroku部署以后URL模式访问能正常发送消息及提醒，但是在Bark App中服务器添加就出现“填写的服务器无效，请重试！网络错误”

**Comment by Finb** [comment]
将地址复制到 手机safari 试试看能不能访问

**Comment by neohob** [comment]
safari , chrome都试了一下，都可以收到提醒消息

**Comment by neohob** [comment]
bark里可以添加 https://xxxx.herokuapp.com/keykeykey/这里填你要发送的消息     这个地址，但是明显是不对的

**Comment by Finb** [comment]
https://xxxx.herokuapp.com/ping 直接用手机safari 打开返回什么
当前手机APP的 DeviceToken（在设置中查看），与配置heroku时填写的是否一样

**Comment by neohob** [comment]
>>>https://xxxx.herokuapp.com/ping 直接用手机safari 打开返回什么
{"code":200,"message":"pong","timestamp":1653970266}

>>>当前手机APP的 DeviceToken（在设置中查看），与配置heroku时填写的是否一样
检查过几次，是直接复制过去的，并且手机浏览器访问 https://xxxx.herokuapp.com/keykeykey/这里填你要发送的消息   是可以收到提醒通知的；就是在bark第一个tab里面增加服务器输入  https://xxxx.herokuapp.com/ 不行

**Comment by Finb** [comment]
看下APP的网络权限

**Comment by neohob** [comment]
> [https://xxxx.herokuapp.com/keykeykey/这里填你要发送的消息](https://xxxx.herokuapp.com/keykeykey/%E8%BF%99%E9%87%8C%E5%A1%AB%E4%BD%A0%E8%A6%81%E5%8F%91%E9%80%81%E7%9A%84%E6%B6%88%E6%81%AF)

加这个地址是可以加的 https://xxxx.herokuapp.com/keykeykey/这里填你要发送的消息，APP网络权限没问题

**Comment by Finb** [comment]
输入 "https://xxxx.herokuapp.com" 试试
后面不要加  /

**Comment by neohob** [comment]
> 输入 "https://xxxx.herokuapp.com" 试试 后面不要加 /

果然好了！
