### ISSUE TITLE
ios端-服务器-修改建议

### ISSUE THREAD

**Issue by SecLoop** [Finb/Bark#151]
Bark IOS端，服务器模块。展示大量测试用例，对强迫症人群不太友好，是否有删除该模块或者手动删除测试用例的计划或想法呢？

**Comment by Whichbfj28** [comment]
这个隐藏到帮助就行了吧。没必要删除。。有的时候还是用得上的

**Comment by JansenChang** [comment]
我也同意这位兄弟的建议！

**Comment by Finb** [comment]
APP 默认进入上次打开的页面，只要不特意进入首页并停留在那个页面，实际使用过程中不会影响到。
但为了保持KISS原则，并不会添加额外的功能去隐藏这些测试用例
