### ISSUE TITLE
iOS（iPadOS）端建议添加“重要通知”功能

### ISSUE THREAD

**Issue by fm812** [Finb/Bark#152]
如题。

**Comment by Lakr233** [comment]
复议。

**Comment by Finb** [comment]
这个通知需要单独向苹果申请权限，但申请已经两个星期了，目前还没有回复。
有结果后我会更新支持上这个功能，但如果被拒绝或一直没回复就不加了

**Comment by WestXu** [comment]
搜了下目前类似app只有pushover支持critical alerts，而且他们也是18年申请，20年才通过。不容乐观啊。
https://blog.pushover.net/posts/2020/2/ios-critical-alerts

**Comment by ffinly** [comment]
希望苹果能尽快审批这个权限，用于告警类通知，非常实用

**Comment by Scribing** [comment]
2年都还没结果吗？

**Comment by Finb** [comment]
权限已批准，我会找时间开发一下这个功能

**Comment by Finb** [comment]
有兴趣的可以先TestFlight试试
https://testflight.apple.com/join/7rA2TUok
重要告警参数 level=critical，设置音量参数 volume=5，取值范围 1-10。
