### ISSUE TITLE
可以实现发送其他指令么？

### ISSUE THREAD

**Issue by cuiliang** [Finb/Bark#16]
类似于IOS捷径那样，调用其他软件。
比如把发送的内容存入到笔记里、打开地图位置什么的。 增加一个uri的字段... 我不懂ios，但是如果能实现的话，可以结合Quicker软件实现很多奇妙的功能。
那样就可以在quicker里设计动作，在ios里执行了。

**Comment by Finb** [comment]
你看看 ifttt jsbox之类的 是不是满足需求(我没用过，不过好像可以做你说的这种需求)，这个App就是简单的推送提醒工具，应该不会加其他功能

CuiLiang <notifications@github.com>于2019年3月2日 周六23:27写道：
