### ISSUE TITLE
有人能教我自动复制怎么实现吗？

### ISSUE THREAD

**Issue by likemuuxi** [Finb/Bark#160]
操作了很长一段时间，没有办法做到作者动图的自动复制推送，搞不懂那个autoCopy参数怎么设置，本人小白，可以有大佬教一下吗，搜索各种教程也没弄明白。
https://api.day.app/key/autoCopy=1

**Comment by Finb** [comment]
苹果权限收紧，已经不能用了

**Comment by miaozilong** [comment]
得要降级苹果系统才行  估计得13及以下的IOS系统才行
