### ISSUE TITLE
好像没办法传递多个参数

### ISSUE THREAD

**Issue by Whichbfj28** [Finb/Bark#161]
比如：传递组跟ico
?group=groupName?icon=http://day.app/assets/images/avatar.jpg
ico不会生效。
老版本的bark服务器。1年多了吧。没更新。不知道现在有没有这个问题。。如果没问题的话。抽空去更新下服务器

**Comment by Finb** [comment]
多个参数需要用&拼接
```
?group=groupName&icon=http://day.app/assets/images/avatar.jpg
```
