### ISSUE TITLE
服务器已经部署成功了，测试也没问题，但是一断开与服务器的SSH连接，就无法推送了。。

### ISSUE THREAD

**Issue by HandingTo1** [Finb/Bark#163]
────────────────────────────────────────────────┐ 
 │                   Fiber v2.36.0                   │ 
 │             http://ip:8080             │ 
 │                                                   │ 
 │ Handlers ............ 26  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ............... 792 │ 

如题，已经出现这个成功的界面了，手机端测试也没问题了，但是一段开SSH连接，就无法推送了。。。

**Comment by Finb** [comment]
运行时后台运行，前台运行断开ssh会终止
