### ISSUE TITLE
请教一下，还有适合系统是iOS12.7能安装的app版本吗？

### ISSUE THREAD

**Issue by zhuaiice** [Finb/Bark#168]
手里的iPhone7还是12.7的版本，AppStore里面的bark软件安装提示需要iOS13以上的版本才能安装！
问下大神，还有适合系统是iOS12.7能安装的app版本吗？可以离线安装的！谢谢

**Comment by Finb** [comment]
没法离线安装，装上了也没推送权限。
你找一下iOS安装旧版本APP的教程，去找依照旧版本的有iOS11的

**Comment by zxysilent** [comment]
> 手里的iPhone7还是12.7的版本，AppStore里面的bark软件安装提示需要iOS13以上的版本才能安装！ 问下大神，还有适合系统是iOS12.7能安装的app版本吗？可以离线安装的！谢谢

先在高版本的ios设备上面安装，然后在你的iPhone7上面下载就行了
