### ISSUE TITLE
有没有人做一个安卓客户端

### ISSUE THREAD

**Issue by rgw5267** [Finb/Bark#17]
1. 读取短信内容，标题为联系人加手机号，内容为短信
2. 读取来电（不清楚能不能获取到）进行提醒接听
这样我就不用随身带着我的安卓机了
ifttt可以做读取短信，但即便后台常驻，提醒还是很不及时或漏提醒。

**Comment by VaslD** [comment]
我可以试试看，需要最低支持的系统版本是多少？

**Comment by rgw5267** [comment]
> 我可以试试看，需要最低支持的系统版本是多少？

我用的8.0，7.0或6.0以上应该占大多数了吧

**Comment by metrue** [comment]
@rgw5267 andriod也有中心化的push notification service 吗？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rgw5267** [comment]
@metrue 安卓不太懂，这个客户端就是我对Bark的一个想法，安卓发Http post

**Comment by akechisatori** [comment]
Android 没有统一的推送服务，除非 APP 一直跑在后台

**Comment by metrue** [comment]
@akechisatori 是的，所以 Android 并不适合 Bark 这种方案。

**Comment by VaslD** [comment]
@akechisatori @metrue Android 有官方的（中心化？）推送服务，只是在中国并不能用。不是重点。

@rgw5267 想要的应该是通过 Bark 把 Android 手机上的重要状态（新短信等）推送到 iOS. 这个需求是 Android > iOS 单向的推送，即使在中国也可以不借助第三方推送 SDK 实现。然而 Android app 需要被各种事件唤起，根据不同人对“跑在后台”的定义可能会被认为一直常驻。

**Comment by rgw5267** [comment]
使用Tasker+Server酱了

**Comment by waynecz** [comment]
> 使用Tasker+Server酱了

大佬求指教 Server 是什么软件

**Comment by joe136685182** [comment]
> > 使用Tasker+Server酱了
> 
> 大佬求指教 Server 是什么软件

搜“Server酱”，一个基于微信推送的push服务。

**Comment by metrue** [comment]
@joe136685182 

bark 有一个 Golang 版本的服务端代码。
https://github.com/Finb/bark-server

**Comment by sakatatoushirou** [comment]
> Android 没有统一的推送服务，除非 APP 一直跑在后台 或者接入一大堆各个平台的 推送 SDK

Android是有的 FCM Google官方推送

**Comment by koneMorris1625** [comment]
> > > 使用Tasker+Server酱了
> > 
> > 
> > 大佬求指教 Server 是什么软件
> 
> 搜“Server酱”，一个基于微信推送的push服务。

谢谢佬答疑解惑
