### ISSUE TITLE
推送链接问题

### ISSUE THREAD

**Issue by 47th0a** [Finb/Bark#174]
我的链接是http://x.x.x.x:1234/key

复制到app内就变成http://x.x.x.x:1234/key/null/
无法正常推送
<img width="288" alt="image" src="https://user-images.githubusercontent.com/96301965/202976169-d6647dc2-5c10-4f02-bdcc-57c204c2bd70.png">

**Comment by Finb** [comment]
不用把key也天上，只填前面一部分。
