### ISSUE TITLE
私有服务器搭建完成后无法添加

### ISSUE THREAD

**Issue by wzc89757** [Finb/Bark#175]
2022-11-27 20:22:09     INFO    192.168.1.2 -> [400] GET      0s /:device_key => /favicon.ico    docker的报错信息
手机端添加不进去 提示失效   本地打开页面提示 {"code":404,"message":"Cannot GET /","timestamp":1669551896}
不知道哪里出了问题  救救我

**Comment by Finb** [comment]
注意看填的是https还是http，把地址复制到safari测试下是否能访问

wzc89757 ***@***.***>于2022年11月27日 周日20:25写道：

**Comment by wzc89757** [comment]
> 

我刚才开启了http   还是显示{"code":404,"message":"Cannot GET /","timestamp":1669694370}      
![image](https://user-images.githubusercontent.com/42182788/204435757-d9573c90-47d8-4537-be24-cf4743af263d.png)
![image](https://user-images.githubusercontent.com/42182788/204435812-e8688cf1-eb99-4a81-92b0-8bf5d044028d.png)
![image](https://user-images.githubusercontent.com/42182788/204435836-4bdf240e-893c-4795-8c15-3187189022b2.png)
我不知道设置的是否有问题？   安装了很多次

**Comment by qkhyjp** [comment]
没问题   用postman请求一下可以请求
