### ISSUE TITLE
添加带 Base Auth 的自定义服务器 URL 时，无法识别

### ISSUE THREAD

**Issue by bekcpear** [Finb/Bark#176]
类似添加 `https://user:password@bark.domain.com/prefix` 这样的地址，报告
```
填写的服务器无效，请重试！网络错误
```

服务器端能收到请求，回复 code `418`，怀疑前缀的 `user:password` 未生效，查 Moya 文档，得到 Base auth 需要使用 `CredentialsPlugin`（ https://github.com/Moya/Moya/blob/master/docs/Authentication.md ），不知是否正确。

**Comment by Finb** [comment]
https://bark.domain.com/prefix 直接这样加，不用加验证，注册不需要验证。

**Comment by bekcpear** [comment]
> https://bark.domain.com/prefix 直接这样加，不用加验证，注册不需要验证。

直接这样子加，它会请求 `https://bark.domain.com/prefix/ping` 这个地址，然后失败，就添加不了 server
