### ISSUE TITLE
添加私有服务器的域名解析地址为IPv6时会提示：填写的服务器无效，请重试!网络错误

### ISSUE THREAD

**Issue by juning98** [Finb/Bark#177]
添加私有服务器的域名解析地址为IPv6时会提示：填写的服务器无效，请重试!网络错误
![IMG_0157](https://user-images.githubusercontent.com/20538542/206886175-10e0699e-4f39-4bc3-964c-8dfe2142e956.jpeg)
浏览器正常：
<img width="465" alt="image" src="https://user-images.githubusercontent.com/20538542/206886229-b4b661c3-d0a2-4b57-80ac-c920b49a5caf.png">

**Comment by juning98** [comment]
不好意思，是我IP配置有误

**Comment by 147miao** [comment]
> 不好意思，是我IP配置有误

您好，请问您是怎么配置的? 我用ip跟您上面的截图出现一样的问题。

**Comment by joji173** [comment]
> 不好意思，是我IP配置有误

您好，请问您是怎么配置的? 我用ip跟您上面的截图出现一样的问题。
