### ISSUE TITLE
如何设置 无任何提醒？

### ISSUE THREAD

**Issue by xuexicn** [Finb/Bark#183]
![image](https://user-images.githubusercontent.com/50934015/218364771-f45850d9-acd3-4f21-8e63-244515e3094d.png)

需求：特殊情况下，不要任何提醒
我在最尾巴增加了  /?level=passive
但是还是会收到 铃声跟条幅提醒，

![image](https://user-images.githubusercontent.com/50934015/218364990-1779c9ea-8926-4f66-ae03-e30a4ea089a3.png)

**Comment by Finb** [comment]
升级到至少iOS15系统
