### ISSUE TITLE
是否支持尾巴上加多个参数呢

### ISSUE THREAD

**Issue by xuexicn** [Finb/Bark#184]
https://api.day.app/Mykey/title/body?level=passive?group=Mygroup

通过网址拼接，加上2个参数，一个静默，一个分组。
?level=passive
?group=Mygroup

或则有简单点的实现方法吗……
渣渣美工一枚。。

**Comment by Finb** [comment]
?level=passive&group=Mygroup
第二个参数开始，用&连接
