### ISSUE TITLE
对app内的弹窗提醒及历史消息的建议

### ISSUE THREAD

**Issue by Stupidarling** [Finb/Bark#191]
在app历史消息模块,如果有新推送会出现弹窗,但此时处于背景的历史消息并不会即时更新,而有些推送并不需要复制或其他操作,这个弹窗提醒反而还需要手动关闭
建议:
1.增加处于app内时,是否开启app内部的弹窗提醒的设置
2. 增加处于app内时,有新推送时继续震动的设置(类似微信app->消息通知->微信打开时->震动,消息提示音)
3. 增加处于app内时,历史消息能即时刷新,不需要手动拉取

**Comment by zelong77** [comment]
附议
