### ISSUE TITLE
[Feature Request] 设置增加“忽略服务器错误的提醒”开关

### ISSUE THREAD

**Issue by yuhangch** [Finb/Bark#193]
在自建服务器增加了权限的验证，所以`.request(.ping(baseURL: ServerManager.shared.currentServer.address))`，会报错。
日常除了测试也基本不会在客户端内发消息，所以希望可以有个开关。

**Comment by Finb** [comment]
可以用nginx或者其他什么工具，单独给  /ping 路径返回一个 `{"code":200,"message":"pong"}` 
因为我需要尽可能减少APP设置项降低使用复杂度，所以暂时不会给应用添加这个配置，需求很小众不是很必要

**Comment by yuhangch** [comment]
Got it，thanks👌
