### ISSUE TITLE
关于app自动打开消息中的url问题

### ISSUE THREAD

**Issue by 6923403** [Finb/Bark#195]
好像app是默认打开的，不知道有没有默认关闭的选项

**Comment by Finb** [comment]
url参数就是这样设计的

Vc ***@***.***>于2023年5月20日 周六18:53写道：

**Comment by 6923403** [comment]
好像app是默认打开的，不知道有没有默认关闭的选项

**Comment by 6923403** [comment]
> url参数就是这样设计的 Vc ***@***.***>于2023年5月20日 周六18:53写道：
> […](#)

刚看到readme上是默认打开的，您这边已经回了，那我先自己把这个url去掉吧，那这个我就关了
