### ISSUE TITLE
关于url跳转带中文参数时效

### ISSUE THREAD

**Issue by wxjer** [Finb/Bark#199]
你好，
例子:https://bark.xxx.xx/key/title/content?url=taobao://s.taobao.com?q=abcd  
如果q的值是英文，则能成功打开，如果是中文则无反应,整个url的参数都用了url编码(utf-8)

taobao%3A%2F%2Fs.taobao.com%3Fq%3Dabcd
taobao%3A%2F%2Fs.taobao.com%3Fq%3D%E8%9A%8A%E9%A6%99

麻烦有时间帮忙看一下

**Comment by Finb** [comment]
首先要规范taobao 的URL,下面是对的
```
taobao://s.taobao.com?q=abcd
```
下面的是错误的，有中文的URL不合法
```
taobao://s.taobao.com?q=中文
```
正确的应该是把中文编码一下
```
taobao://s.taobao.com?q=urlencode(中文)
```
然后拼到bark参数里，因为整个taobao URL有特殊字符，所以也要URL编码一下
```
https://bark.xxx.xx/key/title/content?url=urlencode( taobao://s.taobao.com?q=urlencode(中文) )
```
其中 urlencode 是URL编码的方法
