### ISSUE TITLE
How to add certificate to my server to enable HTTPS connection

### ISSUE THREAD

**Issue by tt-leader** [Finb/Bark#2]
I noticed that in your [tutorial](https://day.app/2018/06/bark-server-document/) you supplied a certificate called `cert-20190308.p12`, and how should I use this to enable server's HTTPS connection?

Thanks.

**Comment by Finb** [comment]
Hi, it's an APNS certificate used to connect your server to Apple's push notification system.
[Bark.go#L163](https://github.com/Finb/go-tools/blob/bc0811390981c7a63e7ea4a591eb1bcd5ed54049/Bark.go#L163)

You can use [acme.sh](https://github.com/Neilpang/acme.sh) to get a free SSL certificate.

**Comment by xtremforce** [comment]
> Hi, it's an APNS certificate used to connect your server to Apple's push notification system.
> [Bark.go#L163](https://github.com/Finb/go-tools/blob/bc0811390981c7a63e7ea4a591eb1bcd5ed54049/Bark.go#L163)
> 
> You can use [acme.sh](https://github.com/Neilpang/acme.sh) to get a free SSL certificate.

How to config using ssl certs?

**Comment by Finb** [comment]
@xtremforce 
https://ruby-china.org/topics/31983
