### ISSUE TITLE
Half of the app is in chinese..and  wont change to English even the system language is changed

### ISSUE THREAD

**Issue by Dcentlill** [Finb/Bark#200]
![image](https://github.com/Finb/Bark/assets/135495703/ba4e1b36-057b-4eda-9ac0-914d96a8ea12)https://github.com/Finb/Bark/assets/135495703/4b8c2cf1-d779-4865-a460-c6eb2315550b

**Comment by ethereal-engineer** [comment]
This is not the app itself but the demo push notification content. If you'd like to see what it says, you could always run it through Google Translate image. However, any content you send and receive will be in English.
