### ISSUE TITLE
IOS 14.5.1版本上， Bark版本1.3.2安装后无法注册设备

### ISSUE THREAD

**Issue by lxh0402** [Finb/Bark#202]
IOS 14.5.1版本上， Bark为从appstore下载的1.3.2版本安装后无法注册设备，请问下是什么原因
![微信图片_20230615112036](https://github.com/Finb/Bark/assets/136667088/e621b8d9-6405-4eb8-8de7-dd42e872d125)

**Comment by Finb** [comment]
你的网络运营商是哪家？ 换个网重启下APP试试

**Comment by lxh0402** [comment]
使用电信宽带以及电信网络都不行。 刚才换了用公司的网络就可以了。 
那请问下这种使用电信宽带时无法注册设备有解决方案吗？

**Comment by Finb** [comment]
ISP的线路问题没办法解决
不过只要注册成功了，之后手机上能不能连就无所谓了，发送端能连就行，不影响使用

**Comment by lxh0402** [comment]
也就是只需要注册成功就可以了，对后续的接收消息不受影响吗？

**Comment by Finb** [comment]
是的

**Comment by lxh0402** [comment]
好的，非常感谢！！！

**Comment by lxh0402** [comment]
再咨询下，要想解决这个电信网络的问题，是不是只能自己建私有服务器才行？
