### ISSUE TITLE
连接了电信wifi，服务器错误了，用5g服务器可以用了，哪里有什么问题

### ISSUE THREAD

**Issue by figure5** [Finb/Bark#204]
![Uploading IMG_1456.jpeg…]()

**Comment by figure5** [comment]
![Uploading IMG_1459.jpeg…]()

**Comment by theodore-abbott** [comment]
于20230705晚，遇到同样问题，使用wifi显示 服务器错误 不能使用推送服务，使用流量正常；地点辽宁沈阳，电信宽带，想知道有解决的方法吗？

**Comment by Finb** [comment]
可以尝试更换服务器域名为 https://api1.day.app ，api1 与api 是同一台服务器，可以无痛切换
