### ISSUE TITLE
不能自动复制

### ISSUE THREAD

**Issue by ldsxp** [Finb/Bark#21]
自动复制跟系统版本有关吗？我加了参数没有效果，加copy的时候手动点复制可以复制后面参数内容，可是不加的时候什么也复制不了

**Comment by Finb** [comment]
App 需要更新到 1.0.4
服务端如果自己部署的，可以重新下载一份最新的试试 
https://github.com/Finb/bark-server/releases

**Comment by ldsxp** [comment]
app版本是最新版，我是在局域网测试的，会有影响吗？自动复制的原理是什么，要app打开吗？还是只要收到通知不管app开没有，都会复制到剪切板？

**Comment by Finb** [comment]
app 不用打开，局域网也没关系。
如果你收到推送后，粘贴板没数据的话，后端程序可能需要更新一下

**Comment by ldsxp** [comment]
我刚才测试了下最新的服务端可以复制，是我自己写的服务端不行，这个参数是怎么给苹果服务器的？我放在了custom参数里面{'automaticallycopy': '1'}，这样不行。

**Comment by Finb** [comment]
需要加这行代码
https://github.com/Finb/bark-server/blob/c10aa55e5792381871a21404a2d5e300ae2ce2c7/server.go#L223

**Comment by ldsxp** [comment]
我用的是python版，来自https://github.com/billzhong/py-bark，其实已经复制了但是内容是空的，比如{"code": 200, "data": {"title": "自动复制推送内容", "body": "", "params": {"automaticallycopy": "1"}}, "message": "发送成功！"}，因为复制的内容是body为空，我一直以为是没有复制成功！

**Comment by ldsxp** [comment]
[python版的后端pybark](https://github.com/ldsxp/pybark)现在可以正常使用了。感谢回复我的问题。

**Comment by billzhong** [comment]
@ldsxp 改了哪能说下吗？

**Comment by ldsxp** [comment]
> @ldsxp 改了哪能说下吗？
需要把参数转换为小写，比如 automaticallyCopy 转为 automaticallycopy，需要注意自动复制内容只会复制body内容。还有改动我不记得了，你可以对比下我源码 https://github.com/ldsxp/pybark

**Comment by billzhong** [comment]
都改好了 😅
