### ISSUE TITLE
可否不推送空白的内容到app

### ISSUE THREAD

**Issue by yidasanqian** [Finb/Bark#213]
单独请求以下链接会推送空白内容
https://api.day.app/{key}

如下图：
![20230908-141540](https://github.com/Finb/Bark/assets/10655188/113d331c-0439-40ca-9180-cfbb265a16f9)

希望不推送空白内容，或者提供个配置是否开启空白内容的推送

**Comment by Finb** [comment]
建议没内容时不要请求。
