### ISSUE TITLE
如何设置像来电一样的提醒？除非主动按掉，否则一直响铃

### ISSUE THREAD

**Issue by xuexicn** [Finb/Bark#217]
您好！
感谢你开发这个应用！

我想请问一下，
因为有的时候一些提醒非常非常重要，
只响铃一声，很容易错过，
如何才能重复响铃，一直响铃，直到我自己主动按掉就停止响铃。
（类似于来电响铃，只有拒接挂断，才不会响铃一样的功能）；

请问这种要怎么设置呀？

**Comment by xuexicn** [comment]
请问有人知道要怎么设置吗？

**Comment by xuexicn** [comment]
anybody can help me ?

**Comment by xywu1990** [comment]
推送端每隔1秒发一个通知，循环20次，模拟

**Comment by Finb** [comment]
可以用TestFlight下载这个支持持续响铃的版本
https://testflight.apple.com/join/7rA2TUok

参数 call=1 ，每条推送会响铃30s，同时收到多条推送时会依次播放
