### ISSUE TITLE
应用图标标记不显示

### ISSUE THREAD

**Issue by erhaodanxia** [Finb/Bark#22]
在手机设置中将 Bark 的 “应用图标标记” 打开后，收到推送后 Bark 图标上不会出现小红点。
此外，假如手机上当前活动的应用是 Bark 的话，不会收到提示。

iOS 版本：10.3.3
Bark 客户端版本：1.0.4

**Comment by Finb** [comment]
设置小红点，发推送时，携带参数 badge=小红点数
例如
```
https://api.day.app/yourkey/test?badge=6
```

苹果的机制是在应用内部显示系统推送，建议不打开APP使用

**Comment by erhaodanxia** [comment]
感谢解答，完美解决问题。
之前对推送机制不了解，还以为是本地计数的。现在才知道原来小红点是这么来的。
再次感谢作者提供这么好的软件！
