### ISSUE TITLE
作者您好,想咨询一下icon能否刷新.

### ISSUE THREAD

**Issue by github410117** [Finb/Bark#223]
目前功能全部正常,先感谢大佬的软件,确实好用.
目前遇到这么一个小问题,通过icon参数下发了通知之后,如果icon变化了,依旧是以前的旧icon,经阅读文档中写到,同样的url地址app会缓存,那有没有什么办法能够清除掉这个缓存呢?
我尝试过删除App(删除所有数据),能够清除掉缓存,但是注册设备就是新的key了,会导致已部署的一些url失效
我想在不删除软件的情况下,能否刷新icon,感谢大佬

**Comment by Finb** [comment]
可以将url改变一下，例如后面加一些不影响url的参数
例如 https://x.com/1.jpg?a=1
后面的 ?a=1 就是添加的无关参数，或者你自由发挥，只要加上参数后仍能正确访问图片地址就行（先自己用浏览器测试下）

另外删除APP后key发生变化，如果还想使用旧的key可以在 APP 服务器列表页面里还原

**Comment by github410117** [comment]
我再想问一下,那个icon的大小是多少合适呢?我40x40,60x60,80x80都试了,圆角图片,感觉都没撑满
