### ISSUE TITLE
iv 中包含 \r\n 导致 Decryption Failed

### ISSUE THREAD

**Issue by zhangyoufu** [Finb/Bark#225]
我使用下面的代码生成随机 iv，使用了很长时间后，遇到偶发的`Decryption Failed`报错。
```python
iv = bytearray(Cryptodome.Random.get_random_bytes(16))
for i in range(len(iv)):
    iv[i] &= 0x7F # ensure ASCII
req_json['iv'] = iv.decode()
```

测试后发现，如果 iv 参数中存在 `\r\n` 会引起 `Decryption Failed` 错误。单独的 `\r` 或者 `\n` 都没有问题。

**Comment by Finb** [comment]
是不是这个导致http报文换行了，建议生成端防止一下这种特殊字符
