### ISSUE TITLE
在IOS17.2.1上使用，通知无法亮屏

### ISSUE THREAD

**Issue by UPToZ-Core** [Finb/Bark#228]
能正在收到通知，并且能够收到通知提示音，但是屏幕不会点亮。

**Comment by Finb** [comment]
* 在手机设置，bark 通知设置中，看下锁定屏幕有没有勾选上
* 检查下其他APP是否能正常亮屏
* 重启手机试试

**Comment by UPToZ-Core** [comment]
好像是系统的问题，我试了一下其他软件好像也不会点亮屏幕，手动点亮屏幕后，是正常能在锁定屏幕上面显示的。
