### ISSUE TITLE
历史消息高亮未读消息

### ISSUE THREAD

**Issue by islercn** [Finb/Bark#237]
现在似乎是无法在外观上区分消息是否已读，感觉不太方便，能否高亮未读消息，以及过滤显示已读/未读消息？

**Comment by Finb** [comment]
暂时没有计划做这个改动，如果之后对消息列表重新设计时可能会考虑，issue 暂时关闭了
另外可以考虑只在系统通知中心查看和管理推送， 通知中心有未读状态
