### ISSUE TITLE
推送中 URL 出现问题时显示其字符串

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [Finb/Bark#24]
如题，这样可以方便调试

**Comment by Finb** [comment]
URL只要遵守`通用规范`即可 ， 很容易调试

需要注意的点
1. 特殊字符需要URL编码，不编码有可能导致URL结构出错或匹配错了路由
```
//例如
https://api.day.app/key/title/{推送内容}
//如果{推送内容}是
"a/b/c/"
//则最后的URL是
https://api.day.app/key/title/a/b/c/
//将找不到对应的路由，后端程序将返回404
```
2. 按定义好的路由路径格式访问

URL出现问题 显示其出问题的部分不好实现

1. URL如果拼错了，请求就到不了服务器

2. 要么到了服务器，但是路由匹配错了，这时也需要你自己根据结果去判断是不是出问题了
你本来想匹配 `A` 路由，但是写错了匹配到了`B`路由， 这时服务器不能确定你是搞错了，只会当成你成功请求了`B`。这是一个正常的成功的请求，不存在错误

3. 参数错了，在返回的json response 中有具体的错误原因

4. 访问了不存在的路径，根据http 状态码即可知道

**Comment by CaptainYukinoshitaHachiman** [comment]
是这样的，我在尝试用 IFTTT 的 Webhook 来推送，这样的话涉及到对请求的编码问题，所以会比较难调试。。。
