### ISSUE TITLE
iOS 17.5.1 Decryption Failed

### ISSUE THREAD

**Issue by paxtonyu** [Finb/Bark#240]
基本情况：安卓手机使用短信转发器，iOS端使用bark两边配置好了encryption，一直到5.26日都能正常接发消息。
问题描述：今天突然接受不到消息，直接在bark app里测试报错提示“Decryption Failed”，目前唯一确定的变量就是升级了iOS系统，安卓端没有更新软件和系统

**Comment by Finb** [comment]
App 端的加密推送测试预览正常情况就是提示Decryption Failed，如果没有收到推送应该去发送端调试下，看下原因。

**Comment by paxtonyu** [comment]
> App 端的加密推送测试预览正常情况就是提示Decryption Failed，如果没有收到推送应该去发送端调试下，看下原因。

好的谢谢

**Comment by Finb** [comment]
从你描述中看，既然能收到预览的推送那接收端应该没啥问题

**Comment by paxtonyu** [comment]
> 从你描述中看，既然能收到预览的推送那接收端应该没啥问题

是的，我小白了，排查了一下发送端发现太久不用联网权限给自动关了，感谢指导！
