### ISSUE TITLE
自定义推送图标无效，请问是怎么回事

### ISSUE THREAD

**Issue by linlihong1984** [Finb/Bark#243]
IOS版本是17.5.1，推送文本和铃声都没问题，但是推送自定义图标时，推送APP中示例的avatar.jpg是正常的，但是将图标地址换成自己的https://pic.imge.cc/2024/07/29/66a744a8e3198.png就不行了，已确认图标地址能正常访问，请问有谁知道是怎么回事吗？

**Comment by Finb** [comment]
url编码一下
https://api.day.app/yourkey/test?icon=https%3A%2F%2Fpic.imge.cc%2F2024%2F07%2F29%2F66a744a8e3198.png
