### ISSUE TITLE
不支持静音按键

### ISSUE THREAD

**Issue by haytoo** [Finb/Bark#244]
能不能实现手机非静音模式的时候有声音，开启静音后就没有声音？

目前设置了铃声的话，不管手机本身是否开启静音，都会有声音提示。
如果设置了铃声为slince，又无论如何都没有声音提示了。

能不能实现跟随手机的设置，非静音模式的时候有声音，开启静音后就没有声音？

**Comment by haytoo** [comment]
勿扰模式也不能将它静音

**Comment by Finb** [comment]
我测试静音模式可以静音呀，建议重启下手机。
