### ISSUE TITLE
如何让加密设置的Iv(初始化向量)可以即时变化？

### ISSUE THREAD

**Issue by JamesMatt** [Finb/Bark#245]
在AES加密模式（如CBC、GCM等）中，IV是一个用来启动加密过程的随机数据块。其作用是确保即使相同的明文和密钥多次加密，也会产生不同的密文，以增强安全性。

IV 的要求和选择：
长度：IV的长度通常需要与加密算法的区块大小一致。例如，对于AES，区块大小是128位（16字节），因此IV的长度应该是16字节。
随机性：IV应该是随机生成的。使用随机IV可以确保加密的安全性。不要重复使用相同的IV，否则会削弱加密强度。
IV的管理：在加密后，IV通常需要与密文一起传送，因为解密过程也需要IV。由于IV并不需要保密（只需要随机），它可以与密文公开传送。

-----

由于目前的Iv栏位要直接输入值，然而安全的Iv应该是要随机且每次都要变化，请问我要如何让这个值可以一直改变？有没有可能新增透过捷径来达成？ 謝謝

**Comment by Finb** [comment]
使用iv参数
?ciphertext=X&iv=X

**Comment by JamesMatt** [comment]
> 使用iv参数 ?ciphertext=X&iv=X

请问方便跟我说这段代码要用在哪边吗？谢谢您

**Comment by Finb** [comment]
在发送加密推送的时候携带

https://bark.day.app/#/encryption
