### ISSUE TITLE
希望增加一个消息推送时间切换显示功能

### ISSUE THREAD

**Issue by ahu** [Finb/Bark#249]
现在比较近的历史消息，显示的推送时间都是相对时间（1 分钟前，2 小时前等）。

希望能增加一个功能，例如点击这个相对时间后，可以切换为显示 2024-09-26 08:29 这种详细时间。再点击详细时间可以切回相对时间。

之所以有这个需求是因为我有时候在短时间内可能有多个同类型业务报错推送，需要具体比对时间以尽快的排查问题，不知道其他人是否也有类似需求。

**Comment by Finb** [comment]
https://testflight.apple.com/join/7rA2TUok
已经更新到 TF 了，正式上线可能会等很久才上。可以用TF版先试试

**Comment by ahu** [comment]
经测，简直不要太完美！提前祝你国庆节快乐～

**Comment by ahu** [comment]
生产环境已测也是 ok 的。
可以标记为 已完成 了，不再是 进行中 了。
