### ISSUE TITLE
显示历史推送信息功能

### ISSUE THREAD

**Issue by yrjyrj123** [Finb/Bark#25]
APP中那个显示使用说明的列表，是否可以增加显示历史推送消息的功能呢？
服务器每次记录下收到的消息，这样点开推送条目后，就可以在APP中看到推送的内容，再也不怕手滑点没了。

隔壁收费的pushover有这个功能。

**Comment by Finb** [comment]
176fdc066985748946c74ba8f827d3227c448754
搞了个临时方案，可以防止手滑
点开推送后也可以把推送添加到备忘录中，应用不保存任何推送信息 
现在可以在App Store更新

如果你想要一个消息列表，可以自己实现一个部署在自己的服务器
发推送的时候携带这个消息列表的URL，这样点击推送将直接打开这URL，就能看到你的消息列表了

**Comment by wahao** [comment]
![](https://mmbiz.qpic.cn/mmbiz_jpg/icWtmsIaSA69CyHTsibIXzplqso95e8IknUAnEC4JAYX8STEVrZAPCTBLeMjibuvu23XJsa1WicKaeEOh5GPlY5RUQ/0?wx_fmt=jpeg)

在小程序加入了这个功能   可以试试

**Comment by jjss520** [comment]
发推送的时候携带这个消息列表的URL，这个怎么实现呢？
