### ISSUE TITLE
Allow image cache to be clear

### ISSUE THREAD

**Issue by Eroyi** [Finb/Bark#250]
It appears that the image is cached based on the filename, which could potentially lead to issues:
1. In a scenario with multiple servers, images with the same name (but different content) could be shared across different servers (e.g., warning_red.png).
2. While testing the push demo, the image will be constantly modified to figure out the best way to present it. I have to change the name repeatedly to ensure that Bark obtains the correct image.

Issue **1** does have a way to work around it, **2** is much more imminent. I've tried reinstalling the app but had no luck, it would be great to have a cache clear button.

**Comment by Finb** [comment]
Add query parameters to your image urls to bypass the cache.

like this:
```
https://x.com/pic.jpg?t=1
```
