### ISSUE TITLE
群组和图标无法共用

### ISSUE THREAD

**Issue by shmilyfuu** [Finb/Bark#252]
您好，请问一下群组和图标无法同时使用是正常的吗？群组在前图标在后则群组生效图标失效，反之则群组失效图标生效。后面拼参数是智能拼一个参数吗？

**Comment by Finb** [comment]
https://api.day.app/your_key/test?group=x&icon=x

**Comment by shmilyfuu** [comment]
> https://api.day.app/your_key/test?group=x&icon=x

感谢解答！我没有仔细阅读教程，非常抱歉。

**Comment by Finb** [comment]
没事
