### ISSUE TITLE
为啥ios用的接口还是老版本的 协议，新版apiv2是给哪个客户端用的

### ISSUE THREAD

**Issue by icetech233** [Finb/Bark#253]
为啥ios用的接口还是老版本的 协议，新版apiv2是给哪个客户端用的

**Comment by Finb** [comment]
那是用于发推送的，不是给APP用到

**Comment by icetech233** [comment]
> 那是用于发推送的，不是给APP用到

那到底是，post json版本，还是 get 版本

**Comment by Finb** [comment]
https://bark.day.app/#/tutorial
