### ISSUE TITLE
提点一些最近使用call=1 当中的建议

### ISSUE THREAD

**Issue by uuneo** [Finb/Bark#257]
1. call=1 的时候下拉消息的时候是否可以考虑关闭铃声，这样正在使用手机时不用一定进入app才关闭铃声
2. call=1的时候，如果是点击了消息，进入到主app，或者点击了action，是否可以考虑移除通知中心的消息，避免造成消息未读的歧义
3. level=critical&call=1 时铃声只能响一次，是否可以考虑直接把铃声拼接到30s，不知道这样会不会解决这个问题

**Comment by Finb** [comment]
#256
