### ISSUE TITLE
能否增加在进入 历史消息 栏自动刷新一下消息

### ISSUE THREAD

**Issue by x2358473** [Finb/Bark#259]
每次从通知是打开 消息，进入历史消息列表都看不到最新的通知。都要手去下拉一下，以刷新列表。

**Comment by x2358473** [comment]
@Finb  个人比较好奇为什么不能每次显示或进入历史消息时都自动刷新下。而是要打开app时计算距离上次刷新时间后再刷新。这个刷新应该不会影响性能。主要但是有时消息比较多时。打开过app后如果不从通知列表点进去，直接打开app就看不到，每次手动下拉一下才能看到。

**Comment by Finb** [comment]
下拉刷新只有20条数据，如果往后翻页找一个什么东西时，只要切一下APP就要重新翻页了。
这一块之后会再优化下，做到及时更新
