### ISSUE TITLE
[BUG] 推送加密中的加密设置UI问题

### ISSUE THREAD

**Issue by Johnserf-Seed** [Finb/Bark#262]
如录屏演示，设置过模式后不点一次算法选项无法切换出GCM模式，多次测试与模式设置无关，均会触发这个bug。

https://github.com/user-attachments/assets/d7fc69ef-eab6-4e7c-8aac-87715034edd8

**Comment by Johnserf-Seed** [comment]
同时切换模式时Iv的占位文本不会更新

**Comment by Finb** [comment]
已修复，原因是GCM并没有准备好示例代码，特意隐藏了
