### ISSUE TITLE
这个文档使用了框架吗，感觉很简约很喜欢，可以开源吗？

### ISSUE THREAD

**Issue by 1607lucky** [Finb/Bark#268]
<img width="1745" alt="image" src="https://github.com/user-attachments/assets/39edbdc4-f9ac-4b58-ab4b-ad1f0dbab7a4" />

**Comment by Finb** [comment]
是这个
https://github.com/docsifyjs/docsify

**Comment by 1607lucky** [comment]
谢谢大佬！！！
