### ISSUE TITLE
从一部ios设备迁移到另一部ios设备之后，推送到哪一个设备变得不确定了

### ISSUE THREAD

**Issue by yuanjs** [Finb/Bark#269]
从一部ios手机全系统迁移到另外一部ios手机后，两个手机的device token是不一样的，但是在Bark服务器页面的设备id，两个手机却是一模一样的，当我向这个id推送信息，发现哪一个设备能收到信息变得不确定了。
不知道为什么不同的device token， 但是设备ID却是一样的。

**Comment by Finb** [comment]
其中一台在服务器列表点击一下 "重置key" ，换一个key使用
