### ISSUE TITLE
是否支持文本base64编码后推送，APP自动解码

### ISSUE THREAD

**Issue by goodryb** [Finb/Bark#27]
现在推送信息是拼接在url里面，如果遇到一些复杂的文本，比如包含换行符，就会导致HTTP调用报错

建议：
1、是否可以在URL参数中增加一个base64标记，如果携带这个标记，则APP对推送内容先解码，然后再进行对应的操作

**Comment by Finb** [comment]
只需要URL编码即可
举一个复杂的例子
把一个带特殊字符的URL当成另外一个URL的参数

1. 首先确保参数URL合法（将URL路径或参数中的特殊字符或中文 URL 编码）
```swift
//参数URL：
let wd = "特殊字符/&%^".encodeURIComponent() 
print(wd) //"%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6%2F%26%25%5E"

let url1 = "https://www.baidu.com/s?wd=\(wd)"
print(url1) //"https://www.baidu.com/s?wd=%E7%89%B9%E6%AE%8A%E5%AD%97%E7%AC%A6%2F%26%25%5E"
```
2. 将url1 当成另外一个URL的参数，因为url1 里面有特殊字符，所以需要对url1编码, （通常应该对所有参数进行编码，编码方法会对需要编码的字符编码，不需要的保持原样）
```swift
let encodeUrl = url1.encodeURIComponent()
print(encodeUrl) //"https%3A%2F%2Fwww.baidu.com%2Fs%3Fwd%3D%25E7%2589%25B9%25E6%25AE%258A%25E5%25AD%2597%25E7%25AC%25A6%252F%2526%2525%255E"

let pushUrl = "https://api.day.app/yourkey/test?url=\(encodeUrl)"
print(pushUrl) //"https://api.day.app/yourkey/test?url=https%3A%2F%2Fwww.baidu.com%2Fs%3Fwd%3D%25E7%2589%25B9%25E6%25AE%258A%25E5%25AD%2597%25E7%25AC%25A6%252F%2526%2525%255E"
```

总结一下就是只需要对URL的参数或路径部分 ，都调用编码方法，确保URL合法 即可

**Comment by goodryb** [comment]
sorry ，可能是我提问给的信息不对，说下我遇到的一个需求，比如说我有个文件，里面有几行(示例)内容
```
测试001
测试002
测试003
```
我想把这个内容通过bark发送到我手机上，现在似乎一次操作是无法完成的，因为这个是多行文本

**Comment by Finb** [comment]
@goodryb 
换行符也算特殊符号，只需要URL编码即可，显示在客户端的就是换行的效果了
你的例子
```swift 
let str = "测试001\n测试002\n测试003".encodeURIComponent()
print(str) //"测试001%0a测试002%0a测试003"
let pushUrl = "https://api.day.app/yourkey/测试001%0a测试002%0a测试003"
```

**Comment by Finb** [comment]
@goodryb
通常，你不需要关心内容是否需要编码，只需要对你要发送的内容，都调用一次URL编码方法即可
let str = {无论从哪读的数据，不管何种格式何种内容}.encodeURIComponent()
再把str 拼接到 pushUrl 即可

**Comment by goodryb** [comment]
@Finb 好的，测试了下应该没问题了

做了一个alfred文本推送  [BarkSendMessage](https://github.com/goodryb/alfred/tree/master/BarkSendMessage)
