### ISSUE TITLE
希望可以将iOS中的短信铃声加入到Bark的铃声中

### ISSUE THREAD

**Issue by NianBroken** [Finb/Bark#271]
如：音符、反弹、怪诞、和弦、滑梯、欢呼、欢迎、接力、门户、沙锤、水滴、通道、重要事件、经典，等等。

希望可以将上述iOS中的所有短信铃声，都加入到Bark的默认铃声中。
![IMG_3361](https://github.com/user-attachments/assets/c3bbdb55-3ba4-4c88-b657-ddf2de0cedaf)
![IMG_3362](https://github.com/user-attachments/assets/ee038058-2a69-4f4e-bb9d-c2f48d7a6aab)

**Comment by Finb** [comment]
现有铃声已经让安装包体积很大了，不会再新增默认铃声
可以自己上传自定义铃声
