### ISSUE TITLE
希望在Bark软件内的消息，可以以图文的形式查看消息。

### ISSUE THREAD

**Issue by NianBroken** [Finb/Bark#276]
由于Bark是免费的，因此存储会导致增加成本。

但是可以增加一个限制，即只能推送小于512kb的图片。

并且会在7天内在服务器清除图片。

这样做既不会增加服务器成本，也能满足用户推送图文消息的需求。

**Comment by Finb** [comment]
不会将图片保存在服务器，但之后会在推送上加上图片地址参数
