### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by ioalloc** [Finb/Bark#3]
Do you have a plan to support for macos desktop?

**Comment by Finb** [comment]
Sorry, I don't have this plan.
There are some better options on macOS such as https://pushover.net/clients/desktop

**Comment by wahao** [comment]
You can use Electron-igot to manage and get message on Mac OS

**Comment by ahu** [comment]
> Sorry, I don't have this plan.
> There are some better options on macOS such as https://pushover.net/clients/desktop

我也想要 mac 端。

pushover 我也有，但是即便是付费的也有频次限制，这没法弄...
楼上的 iGot 我看就是为了让大家多看广告的，这也没法弄...
