### ISSUE TITLE
做了个小程序端的插件 支持历史记录查看  喜欢的可以试试  

### ISSUE THREAD

**Issue by wahao** [Finb/Bark#31]
喜欢的可以试试       支持多提issues哦    

[Bark-MP-helper](https://github.com/wahao/Bark-MP-helper)

![](https://mmbiz.qpic.cn/mmbiz_jpg/icWtmsIaSA69CyHTsibIXzplqso95e8IknUAnEC4JAYX8STEVrZAPCTBLeMjibuvu23XJsa1WicKaeEOh5GPlY5RUQ/0?wx_fmt=jpeg)

**Comment by jjss520** [comment]
小程序只能用你的服务器，能改成自定义吗？

**Comment by wahao** [comment]
> 小程序只能用你的服务器，能改成自定义吗？

暂时还不支持哦     小程序需配置https白名单。         服务器会存储用户的推送数据，如果涉及重要隐私、担心数据安全，请先暂时不要通过小程序内提供url推送

**Comment by jjss520** [comment]
老哥，用docker搭的，怎么像作者说的，消息列表链接怎么弄
