### ISSUE TITLE
真心觉得app里应该保留接收到的消息

### ISSUE THREAD

**Issue by luckfu** [Finb/Bark#34]
当发送一条以上的消息时，这种阅后即焚的模式，很容易丢掉上一条信息的阅读机会。强烈建议ios的app里在本机保存一下历史消息

**Comment by wahao** [comment]
![](https://mmbiz.qpic.cn/mmbiz_jpg/icWtmsIaSA69CyHTsibIXzplqso95e8IknUAnEC4JAYX8STEVrZAPCTBLeMjibuvu23XJsa1WicKaeEOh5GPlY5RUQ/0?wx_fmt=jpeg)

在小程序加入了这个功能   可以试试

PS：服务端会保留推送消息内容哦~~~
