### ISSUE TITLE
IOS 13.2 无法获取 key

### ISSUE THREAD

**Issue by Captain-Alan** [Finb/Bark#37]
已重新关闭开启通知权限, 依然无法获取 key

**Comment by Finb** [comment]
我用iOS13.2 测试后是正常的，
确保 https://api.day.app/ping 能访问，这是台湾的服务器国内有些地方访问可能不稳定
确保给了APP网络权限

**Comment by Captain-Alan** [comment]
网络权限是给了的
前些天可用, 但好像是升级ios后, 最近发现quicker无法发送数据到手机, 当时以为是key不对, 之后又卸载重装了, 但仍显示如图"Your Key", 反复register device 仍不起作用

![65A71ADB-2CF1-4AA3-9B7B-79F064.png](https://i.loli.net/2019/11/06/zWanlGAfS7XJBjY.png)

**Comment by Finb** [comment]
@Captain-Alan 点右上角+号，把服务器地址换成 https://api2.day.app:4443 试试

**Comment by Captain-Alan** [comment]
依然没有获取到key
![1](https://i.loli.net/2019/11/07/nTrICFVQiDXpEwB.png)

**Comment by Captain-Alan** [comment]
升级到13.2.2, 功能正常了
