### ISSUE TITLE
HTTPS证书是否有变动

### ISSUE THREAD

**Issue by MrQcc** [Finb/Bark#38]
今天开始程序突然报证书验证失败，Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))

**Comment by Finb** [comment]
是有可能，最早的程序内嵌的证书可能已经过期了，苹果给的证书有效期最长只能一年。

你可以暂时从github下载新的程序，现在内嵌的证书有效期到2020年2月29号，我会提前两个月(今年12月月底)更新新证书，到时候还请再更新一次，就可以用一年了

MrQcc <notifications@github.com>于2019年12月7日 周六14:56写道：

**Comment by Finb** [comment]
我擦，原来是我的服务器出问题了
服务器的 acme.sh 自动更新证书停了, 非常感谢告知
