### ISSUE TITLE
是否发送成功

### ISSUE THREAD

**Issue by wnma3mz** [Finb/Bark#39]
您好，有的时候设备长时间无网络，之后联网后无法收到之前推送的通知。能否添加一个发送成功的标记or状态码？方便判断是否需要重发。

或有其他解决方案烦请告知，感谢！

**Comment by Finb** [comment]
后端仅与苹果APNS通信，无法知道APNS是否将推送成功推到设备上,所以没办法给发送成功状态码

短暂无网络应该会在联网后收到推送，长时间无网络我并不清楚推送是否一定会被丢弃

或许之后可以在推送抵达设备后，设备请求一个回调URL通知你的服务器，你根据回调URL的抵达时间判断是否成功推送
但我觉得这种好像又没必要，因为使用起来会比较复杂，这个APP是想非常简单的推送一些简单的提醒

**Comment by wnma3mz** [comment]
感谢您的回复。在推送大量通知（10条以上）时，设备长时间断网后再恢复，只能收到一条通知。我后续会想办法绕过这个问题，谢谢！
