### ISSUE TITLE
api.day.app 能不能开放跨域

### ISSUE THREAD

**Issue by ficapy** [Finb/Bark#42]
浏览器写了个小脚本，发送通知用了Bark. 但是提示CORS错误
后端能否允许一下跨域请求?

**Comment by ficapy** [comment]
先找了个工具临时避开CORS https://github.com/Shivam010/bypass-cors

不过最好还是开放一下，避免折腾

**Comment by Finb** [comment]
加上了，可以再试一下，看是不是有啥问题

**Comment by ficapy** [comment]
@Finb 有请求头的不行
Request header field xsrf is not allowed by Access-Control-Allow-Headers in preflight response
需要指定允许所有

**Comment by Finb** [comment]
咋会有 xsrf 请求头~
我把Access-Control-Allow-Headers 删掉了，但我不知道浏览器还认不认了。
你再试试，如果还有问题，你发个 qq 号到我的邮箱吧，我们qq上调一下

**Comment by ficapy** [comment]
现在可以了，多谢～～
