### ISSUE TITLE
建议添加历史信息清空功能

### ISSUE THREAD

**Issue by AragonSnow** [Finb/Bark#45]
Bark添加了历史信息功能，实在太棒了。但是推送多了要查看的时候会很麻烦，一条条点击删除太累了，能否添加一个清空历史信息的功能？

**Comment by Finb** [comment]
后面会增加清理相关的功能，

现在我建议要删的通知可以指定不保存在本地。然后使用系统的通知中心管理这些暂时的推送

有两种方法
1. APP中设置默认保存推送，发推送时，推送不需要保存时就添加参数isArchive=0
2. APP中设置默认不保存推送，发推送时，推送需要保存就添加参数isArchive=1
