### ISSUE TITLE
考虑在通知内容中包含 图片 视频 音频 等内容吗？

### ISSUE THREAD

**Issue by chenbaocn** [Finb/Bark#5]

**Comment by Finb** [comment]
应该不支持~
推送只能文本，其他内容必须上传到互联网得到一个URL，在收到推送时手机去主动下载这个URL，下载完毕后再呈现推送内容。
但这里面有很多限制，例如总共只能有30S的运行时间，呈现的推送界面需要用户下拉推送打开，很多操作都不能用

所以还不如 直接把 图片视频的URL 当成文本推送过去，下拉推送后 URL是可点击的，之后跳转到Safari就可以做相对应的操作了

**Comment by 1273082756** [comment]
> 应该不支持~
> 推送只能文本，其他内容必须上传到互联网得到一个URL，在收到推送时手机去主动下载这个URL，下载完毕后再呈现推送内容。
> 但这里面有很多限制，例如总共只能有30S的运行时间，呈现的推送界面需要用户下拉推送打开，很多操作都不能用
> 
> 所以还不如 直接把 图片视频的URL 当成文本推送过去，下拉推送后 URL是可点击的，之后跳转到Safari就可以做相对应的操作了

请问考虑支持一下Markdown吗
