### ISSUE TITLE
post请求发送通知失败，一直是404

### ISSUE THREAD

**Issue by lxk0301** [Finb/Bark#54]
不知是我使用不对？ 还是什么问题？ 请帮忙看看

![image](https://user-images.githubusercontent.com/21308593/98085841-e3d2f080-1eb8-11eb-8669-68bd69e52d8e.png)
![image](https://user-images.githubusercontent.com/21308593/98085953-06fda000-1eb9-11eb-9760-15a64d8460c2.png)

**Comment by Finb** [comment]
请求 url 后面加个 / 试试
例如
https://api.day.app/yourkey/  <- 这个

**Comment by lxk0301** [comment]
感谢， 已经成功， 但是提示我推送内容太多，用get也经常这样子提示。以为改成post请求会无此限制

![image](https://user-images.githubusercontent.com/21308593/98088777-d7e92d80-1ebc-11eb-9c8d-99c639714c3f.png)

**Comment by lxk0301** [comment]
post请求， 如果title和body不进行编码，虽然能推送成功， 但是 APP就会收到`无推送文字内容`

![image](https://user-images.githubusercontent.com/21308593/98089076-3a422e00-1ebd-11eb-9a5d-d927212c98a9.png)

**Comment by lxk0301** [comment]
基于上述问题， 不知是否有什么好的解决办法呢？

**Comment by Finb** [comment]
这是苹果推送的限制，推送的字不能非常多，需要适当的裁剪

你可以把字放在某个地方，然后推送 摘要+ URL

**Comment by lxk0301** [comment]
好的， 了解。 多谢解答

**Comment by lxk0301** [comment]
> 这是苹果推送的限制，推送的字不能非常多，需要适当的裁剪
> 
> 你可以把字放在某个地方，然后推送 摘要+ URL

对了 这问题 (编码后推送失败，提示URL过大)我还想问问  ，同样长度的推送内容， 我用get请求推送成功， 反而用post请求推送失败

**Comment by Finb** [comment]
> > 这是苹果推送的限制，推送的字不能非常多，需要适当的裁剪
> > 你可以把字放在某个地方，然后推送 摘要+ URL
> 
> 对了 这问题 (编码后推送失败，提示URL过大)我还想问问 ，同样长度的推送内容， 我用get请求推送成功， 反而用post请求推送失败

这个原因我也不太清楚了，最好还是再减少些长度，多余的裁切掉

**Comment by lxk0301** [comment]
> > > 这是苹果推送的限制，推送的字不能非常多，需要适当的裁剪
> > > 你可以把字放在某个地方，然后推送 摘要+ URL
> > 
> > 
> > 对了 这问题 (编码后推送失败，提示URL过大)我还想问问 ，同样长度的推送内容， 我用get请求推送成功， 反而用post请求推送失败
> 
> 这个原因我也不太清楚了，最好还是再减少些长度，多余的裁切掉

好的👌
