### ISSUE TITLE
可以给Chrome的插件图标换个颜色吗?

### ISSUE THREAD

**Issue by ali50m** [Finb/Bark#57]
当前的灰色图标在Chrome设置为Dark主题下,会变得看不清楚.
![image](https://user-images.githubusercontent.com/9393831/102031568-55278c80-3df1-11eb-96f0-fafd657b3565.png)

**Comment by Finb** [comment]
可以给这位大佬反馈一下~
https://github.com/xlvecle/Bark-Chrome-Extension

**Comment by ali50m** [comment]
> 可以给这位大佬反馈一下~
> https://github.com/xlvecle/Bark-Chrome-Extension

OK, 已转发. 谢谢~
