### ISSUE TITLE
自动复制推送内容失效

### ISSUE THREAD

**Issue by wddclass** [Finb/Bark#58]
在最新的iOS14.3系统中 自动复制推送内容失效了

**Comment by Finb** [comment]
尝试下重启下手机试试？
某些情况下，系统的推送扩展将失效，导致代码不运行。

**Comment by wddclass** [comment]
> 尝试下重启下手机试试？
> 某些情况下，系统的推送扩展将失效，导致代码不运行。

可以了，谢谢
