### ISSUE TITLE
添加服务器： 找不到key对应的DeviceToken key

### ISSUE THREAD

**Issue by ngxlua** [Finb/Bark#6]
你好 作者，

应用端只有一个添加服务器， 添加时始终出现错误，因为没有 DeviceToken

实际的请求中，可以发现 app 发起的请求也没有携带这个参数， 是哪里有疏漏？

**Comment by Finb** [comment]
如果是自己搭建的后端服务器，则填写你后端地址即可，不需要加任何path

如果你用我提供的默认服务器，只是发送推送
打开APP 点注册，会出现一些教程示例，上面有写请求地址， 你直接复制就可以使用了，请求这个URL就会收到推送

**Comment by ngxlua** [comment]
> 如果是自己搭建的后端服务器，则填写你后端地址即可，不需要加任何path
> 
> 如果你用我提供的默认服务器，只是发送推送
> 打开APP 点注册，会出现一些教程示例，上面有写请求地址， 你直接复制就可以使用了，请求这个URL就会收到推送

谢谢回复，是我疏忽了代理配置，已经可以了。
