### ISSUE TITLE
苹果手机能否支持图标标记？

### ISSUE THREAD

**Issue by zxp3721** [Finb/Bark#60]
您好，苹果手机使用bark时有时直接指纹解锁进入了手机，进入手机后由于没有“图标标记”，所以根本就没有发现有重要的通知，必须要下滑显示历史通知才能发现有通知，但像微信或短信等软件，由于支持图标标记，显示有几条信息未读，很容易就能发现有通知信息，希望能增加“图标标记”的支持，即有多少条未浏览的通知，如果有人不喜欢这个功能可以增加个开关，也可以在url中增加参数，携带参数的条目支持图标标记提示，这样不会错过重要的通知，希望能支持该功能，谢谢。
![qqq20210108120549](https://user-images.githubusercontent.com/9151620/103973218-e3512180-51a9-11eb-9d03-c938780a8f3d.jpg)

**Comment by fsnhljz** [comment]
希望是APP自带，若用参数的话，需等其他软件适配提供。

**Comment by harryzcy** [comment]
请求中添加 `badge` 已经可以了
