### ISSUE TITLE
历史消息无法保存

### ISSUE THREAD

**Issue by RayJiang16** [Finb/Bark#66]
App内设置了自动保存，url中isArchive=1参数加或不加都不会保存，历史消息页面一直是空白的。
通过首页-自动保存通知消息，链接访问也是一样，通知能收到，历史消息页面就是空白。

iOS：14.3
App：1.1.2

**Comment by Finb** [comment]
推送扩展不能运行，重启下手机可以解决

**Comment by RayJiang16** [comment]
解决了，谢谢
