### ISSUE TITLE
历史消息白屏，不显示内容

### ISSUE THREAD

**Issue by zyt09** [Finb/Bark#68]
我在两台 iPhone 上都分别安装了，指向了同一个服务器。

一个手机可以收到消息，但是无论消息是否制定 isArchive 还是默认是否开启，都无法保存的历史记录。另外一台默认就保存历史消息。

所以没有找到稳定 repro 这个 bug 的方法，但是还望作者看一下能否解决。

**Comment by Finb** [comment]
这个好像是个系统BUG，推送扩展运行不了。
重启一下就能解决

**Comment by zyt09** [comment]
谢谢！奇迹般的解决了！那么下次重启会不会再变坏呢？

**Comment by Finb** [comment]
目前看应该不会

**Comment by zyt09** [comment]
好的，再次感谢！

**Comment by chinobing** [comment]
重启了手机依旧无法保存消息，而且首页不显示收到的信息，但弹屏是正常显示信息的
