### ISSUE TITLE
切换服务器地址后，历史记录失效

### ISSUE THREAD

**Issue by dss886** [Finb/Bark#69]
重启手机后恢复，再次更改地址后，还会再次失效。。。

**Comment by dss886** [comment]
失效的意思是收到消息后不记录在历史记录中了，原有的历史记录不受影响

**Comment by Finb** [comment]
先重启解决吧，这个原因我也在找， 不知道是系统机制还是系统BUG。

推送历史 是由 推送服务扩展 在设备本地记录的。
推送服务扩展由系统在收到推送时执行，某些原因导致推送服务扩展没有运行

**Comment by dss886** [comment]
@Finb 找到原因了，我在自己实现的服务端中少传了一个mutable-content=1，没有这个字段就不会被记录到App的历史记录中，加上就好了
