### ISSUE TITLE
可以保存推送历史吗

### ISSUE THREAD

**Issue by cwup** [Finb/Bark#7]
如题如题，谢谢！很好用

**Comment by cwup** [comment]
可以考虑增加copy and open in Safari选项

**Comment by Finb** [comment]
你好，推送历史可以使用系统的通知中心，配合通知分组可以简单的管理推送内容。

收到推送时 下拉推送（或在通知中心左滑查看推送）有一个 复制 按钮，点击即可复制推送内容
发推送时，携带参数 automaticallyCopy=1， 则收到推送时，推送内容会自动复制到粘贴板
发推送时, 携带copy参数， 则上面两种复制操作，将只复制copy参数的值

示例
https://api.day.app/yourkey/验证码是9527  //复制验证码是9527
https://api.day.app/yourkey/验证码是9527?copy=9527 //复制9527
https://api.day.app/yourkey/验证码是9527?copy=9527&automaticallyCopy=1 //收到推送时，自动复制9527，无需手动操作

发推送时,携带url参数 ，点击推送则会打开连接（应用内打开，但和在Safari打开是一样的，共享cookie等）工具栏上有在Safari打开的按钮

示例
https://api.day.app/yourkey/百度网址?url=https://www.baidu.com

**Comment by cwup** [comment]
如何桌面端设置默认发送默认复制呢，不用每次添加auto参数😆

**Comment by Finb** [comment]
我之前修改了一下，让插件发送推送时自动加上automaticallyCopy参数
相当于把电脑内容推送到iPhone的粘贴板

下载地址
https://github.com/Finb/Bark-Chrome-Extension/releases/tag/0.0.1
效果展示
![](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fyaqyhzdnxg30660dcu0h.gif)

**Comment by cwup** [comment]
哇羡慕dalao（俺是跨考计算机啥也不会的渣渣😢

**Comment by xlvecle** [comment]
@cwup 这个feature我之前已经把 @Finb 大神的PR合并了，目前应该是支持的，如果不支持可能需要更新下服务端

**Comment by zhangnew** [comment]
感谢大佬开发这么好用的工具，还是希望有个历史记录的功能，谢谢！
