### ISSUE TITLE
收到了别人的推送

### ISSUE THREAD

**Issue by yoodz** [Finb/Bark#70]
早上没有操作，自动收到一条推送。有遇到这样情况的吗？

**Comment by SokaOfficial** [comment]
有的，而且有时候收到的内容是空的。怀疑是有人或设备监控了我的流量，然后去扫这些URL导致的触发。

**Comment by Finb** [comment]
一般来讲是不会有这种情况的，每次推送都需要携带你设备上的deviceToken，这个不泄漏的话是不能给你推送的。

你可以检查下以下几种常见的情况
1. 浏览器里有推送地址的标签，浏览器启动时自动重新请求
2. 使用了一些定时工具或向第三方工具提供了推送url
3. 使用了nginx等反代服务器将32位key重写成了常见关键词
4. ...

如果确保任何可能泄漏deviceToken的地方都没有，则卸载App重置一下deviceToken

**Comment by yoodz** [comment]
感谢回复。
![image](https://user-images.githubusercontent.com/17819348/107172283-ec7b1b80-69ff-11eb-9bc0-71e84b0cb86a.png)

**Comment by bigtan** [comment]
你要是把推送链接复制到qq或者telegram  这些软件会访问这个地址  获取内容，然后触发了推送。

**Comment by happysoul** [comment]
很多软件都有网址检测功能，说白了就是替你先访问一次看看里面内容，如果不健康就留底儿记录，后面就等查水表吧
