### ISSUE TITLE
飞行模式或者没有信号时，再次联通后，仅收到最新一条

### ISSUE THREAD

**Issue by hyorigo** [Finb/Bark#72]
我不太懂 Apple 具体的推送机制，请问这是系统的限制？还是软件的bug呢？

**Comment by Finb** [comment]
是特性，默认推送有效期是实时，没收到就被APNS丢弃了。
已经设置为了 1天 ，APNS会保留没发送成功的推送1天时间。 

https://github.com/Finb/bark-server/commit/0152eabffb059e10224123570b365d9f1406df44
后端代码已经修改，自建服务器的更新一下即可。
但公共服务器还没部署

**Comment by hyorigo** [comment]
@Finb 谢谢！请问 `finab/bark-server` 这个 Docker 镜像是否更新了呢？

**Comment by Finb** [comment]
更新了， latest 和 v2.0.0 都行

**Comment by hyorigo** [comment]
好的，谢谢！更新之后，发现和 v1 版本不再兼容了，不支持 POST 方式发送报文了。

**Comment by Finb** [comment]
抱歉，确实遗漏了一个路由。

https://github.com/Finb/bark-server/commit/863f9928e688feface087a273aeb8f90d3164e65
已经加上了，你再pull下试试

**Comment by hyorigo** [comment]
谢谢，我读了一下代码，发现除了 POST 之外，另一个兼容性的问题导致了错误——

* v1 支持 form 的方式提交信息：https://github.com/Finb/bark-server/blob/v1.0.2/server.go#L76-L86
* v2 已经不再支持 form 的方式：https://github.com/Finb/bark-server/blob/master/route_push.go#L51-L99

希望能推荐一个完美兼容 v1 和 v2 的报文提交方式。另外，就是除了 `ping` 是否有其他合适方式判断 server 运行的版本，以便客户端做出兼容性应对。

**Comment by Finb** [comment]
v2也支持的 form 提交的，你可以测试一下。
例如
```
curl -X "POST" http://0.0.0.0:8080/key/ -d 'body=hello'
```
v2增加了一个 /info

**Comment by hyorigo** [comment]
OK 我来试一下 `docker pull finab/bark-server:v2.0.1` 版本。

**Comment by hyorigo** [comment]
@Finb Thanks! Fixed!
