### ISSUE TITLE
[question] 关于推送次数的limit限制

### ISSUE THREAD

**Issue by marlonfan** [Finb/Bark#73]
这款软件非常Nice, 解决了我想要自定义一些通知的需求. 但是有个问题想了解下.

目前软件有推送Limit的限制么?   每个人每天的调用上限是多少次呢~  另外就是有没有Markdown渲染的通知...

再次感谢👻

**Comment by Finb** [comment]
没有限制，但超出公共服务器处理能力时将推送失败。
如果想稳定，建议自己搭建服务端，1C1G1M的云主机每天能推百万次
