### ISSUE TITLE
通知框中多条消息，点击其中一条会进入app弹窗进行操作，但是其他几条就会消失

### ISSUE THREAD

**Issue by wensiyuansix** [Finb/Bark#74]
RT

**Comment by wensiyuansix** [comment]
能否进入后，依然查看其他几条？

**Comment by Warkeeper** [comment]
这个功能本身就有，打开 APP 左上角，有个可以查看历史消息的按钮

**Comment by happysoul** [comment]
左上角点历史，然后右上角齿轮，选上默认保存就能一直存储历史数据
要不就在请求上加上保存的参数，app里面有例子---自动保存通知消息

**Comment by harryzcy** [comment]
[commit 102a8f2](https://github.com/Finb/Bark/commit/102a8f285db9d712a6112cdb44fa7e517d0154ed) 解决了
