### ISSUE TITLE
macOS client?

### ISSUE THREAD

**Issue by zyt09** [Finb/Bark#75]
请问是否有计划开发 macOS 版本的推送客户端？或者让 macOS 和 iOS 推送和内容的自动同步？

**Comment by Suchun-sv** [comment]
我遇到的情况是开发的时候是想看到服务器的提示信息，传到手机上不如传到电脑上方便。

**Comment by mobilelifeful** [comment]
> 请问是否有计划开发 macOS 版本的推送客户端？或者让 macOS 和 iOS 推送和内容的自动同步？

找到https://github.com/RayJiang16/Bark-Mac
好像自己build 需要开发者 账号，  
（也需要 macOS 版本的推送客户端。）

**Comment by mobilelifeful** [comment]
@Suchun-sv 
推荐 
https://github.com/easychen/pushdeer
