### ISSUE TITLE
客户端没有同步升级适配bark-server的API V2吗？

### ISSUE THREAD

**Issue by pppscn** [Finb/Bark#79]

**Comment by Finb** [comment]
客户端不用适配，直接用V2就行。

**Comment by pppscn** [comment]
url上的key就是v2的device_token，对吗？

**Comment by Finb** [comment]
device_token 是 苹果推送标识码，是一一与设备对应的，但是会动态改变

url上的 key 是为了在device_token改变是时，推送URL不用跟着改变，
key 与  device_token  对应， device_token改变时，key会指向新的device_token

**Comment by pppscn** [comment]
感谢解答
