### ISSUE TITLE
Add a custom server URL, If your server listening port isn't 80 or 443, It will occur "Invalid Server URL!"

### ISSUE THREAD

**Issue by ky0nch3ng** [Finb/Bark#8]
In chrome-extension setting page:

[chrome-extension://pmlkbdbpglkgbgopghdcmohdcmladeii/options.html](chrome-extension://pmlkbdbpglkgbgopghdcmohdcmladeii/options.html)

Add a custom server URL, If your server listening port isn't 80 or 443, It will occur "Invalid Server URL!"

![](https://i.imgur.com/Ip1KwwQ.png)

```
curl https://xxxx.com:4321/ping

{"code":200,"data":{"version":"1.0.0"},"message":"pong"}%
```

**Comment by Finb** [comment]
你好，这个chrome插件是这个项目的，我没有仔细研究过代码，不太清楚原因
https://github.com/xlvecle/Bark-Chrome-Extension

可以请 @xlvecle 大神看看

**Comment by ky0nch3ng** [comment]
@Finb 
![](https://i.imgur.com/wI79hyG.png)

请问这个 key 是什么？

服务端启动也只显示

```
2019/02/19 17:20:07 Serving HTTP on 0.0.0.0:4320
```

**Comment by Finb** [comment]
@ky0nch3ng 
就是代表设备的标识符。
服务器用这个key 获取你设备的 DeviceToken，然后用这个DeviceToken给Apple推送服务器发推送，你的设备就会收到推送

你注册时，会随机生成一个Key，并和你设备的 推送DeviceToken 一起发送到服务器保存起来
App的 DeviceToken并不是固定不变的，可能会变化。 有变化时，会将变化更新到服务器
Key 会一直绑定在最新的DeviceToken上

如果你自己部署了后端，需要点右上角 + 号 按钮， 修改客户端的后端服务器地址

**Comment by ky0nch3ng** [comment]
@finb
OK，解决了，多谢

**Comment by ky0nch3ng** [comment]
@Finb 

1. 发现 iPhone 可以收到自定义发送的通知，但是 App 内无法显示，都还是实例的内容
2. 希望增加 删除 App 内自定义发送的通知 功能

**Comment by Finb** [comment]
这是一个非常轻量的推送提醒App, App内部不保存内容

使用时，也不需要打开App，在系统的通知中心就能操作
查看、删除、复制等直接在推送界面操作就行了

**Comment by ky0nch3ng** [comment]
了解~多谢！
