### ISSUE TITLE
能否支持query参数或body参数吗

### ISSUE THREAD

**Issue by huluohu** [Finb/Bark#80]
如题，能否支持将标题和内容放到query参数里或body里？

**Comment by Finb** [comment]
可以的
例如
```
https://api.day.app/yourkey/?title=test
```
参数名是 title 和 body
post 也是这俩

**Comment by huluohu** [comment]
> 可以的
> 例如
> 
> ```
> https://api.day.app/yourkey/?title=test
> ```
> 
> 参数名是 title 和 body
> post 也是这俩

可以，非常感谢！
