### ISSUE TITLE
自动复制内容到剪贴板在 iOS 14.5 失效了

### ISSUE THREAD

**Issue by axelburks** [Finb/Bark#81]
参数：automaticallyCopy=1 
iOS：iOS 14.5
Bark：1.1.2
表现：收到通知后不会自动复制到剪贴板，必须点击通知跳转到 APP 内并点击复制内容才会复制到剪贴板

**Comment by Finb** [comment]
重启下手机试试

**Comment by axelburks** [comment]
已经多次重启试过了

**Comment by Finb** [comment]
使用的后端服务是公共服务器么？还是自建的

**Comment by axelburks** [comment]
APP 内置的公共服务器

**Comment by Finb** [comment]
能否提供一个请求url给我测试下？

**Comment by axelburks** [comment]
可以，请问如何私下给你？

**Comment by Finb** [comment]
只需给我参数就行，隐私信息打码即可
或直接发我邮箱 heyfiniks@gmail.com

**Comment by axelburks** [comment]
啊，是想确认下我使用的格式是否正确？
我已经通过 APP 内置的链接试过了，都是有问题的。
https://api.day.app/xxxxxxxxxx/自动复制推送内容?automaticallyCopy=1&copy=optional

**Comment by Finb** [comment]
那参数应该没问题

你看一下通知历史记录能保存么

**Comment by axelburks** [comment]
能保存，目前看只是自动复制有问题

**Comment by Finb** [comment]
那奇怪了，能保存那应该复制也没啥问题啊~

你是不是有其他Apple设备，开启了剪贴板同步？ 但一般这个也只是在有复制操作时会干扰一下。

**Comment by axelburks** [comment]
是的，但是我并没有在其他设备进行复制操作

**Comment by axelburks** [comment]
找了台 iOS 14.3 试了下没有问题

**Comment by Finb** [comment]
等14.5发布后我再看一下吧
总不可能14.5限制了推送扩展访问剪切板吧

**Comment by HankPPeng** [comment]
14.4也不能。收到推送，但粘贴时是“%clipboard%”，而且进入Bark后点复制也不能复制到内容，依旧是“%clipboard%”。

**Comment by Finb** [comment]
> 14.4也不能。收到推送，但粘贴时是“%clipboard%”，而且进入Bark后点复制也不能复制到内容，依旧是“%clipboard%”。

是chrome插件吧？你卸载插件再重装试试，chrome插件发的就是“%clipboard%” ，自然复制的就是这个了。
具体为啥你可以像插件作者反馈一下。

**Comment by HankPPeng** [comment]
> > 14.4也不能。收到推送，但粘贴时是“%clipboard%”，而且进入Bark后点复制也不能复制到内容，依旧是“%clipboard%”。
> 
> 是chrome插件吧？你卸载插件再重装试试，chrome插件发的就是“%clipboard%” ，自然复制的就是这个了。
> 具体为啥你可以像插件作者反馈一下。

倒不是插件的问题，插件能正常使用。是脚本使得出现上述问题，具体代码如下：

;Made by Tp
;使用前请务必在同一个目录下建立「url.txt」文档，并以「https://api.day.app/xxxxxxxxx/」的格式将推送链接粘贴进去。
^!c::
FileRead, url, url.txt
copy := "?automaticallyCopy=1&copy=%clipboard%"
clipboard = %clipboard%
finalURL = %url%%clipboard%%copy%
req := ComObjCreate("WinHttp.WinHttpRequest.5.1")
req.Open("POST", finalURL)
req.Send()

难道升级了14.5后插件也出现问题了吗...

**Comment by Finb** [comment]
@HankPPeng 
和iOS 14.5应该没关系，你打印一下 finalURL ，看下最后请求的URL是什么样的.

**Comment by HankPPeng** [comment]
> @HankPPeng
> 和iOS 14.5应该没关系，你打印一下 finalURL ，看下最后请求的URL是什么样的.

好的，我是iOS14.4，用插件是正常使用的。不过，脚本却失效了，也就很奇怪，因为之前一直用，并不存在这个问题，所以我以为碰上所提的问题了。脚本也是很久没更新了，我对Hankoff实在不熟悉...不过，我问题算是解决。
脚本的地址：https://github.com/authorTp/Handoff4Windows

**Comment by axelburks** [comment]
又过了几个 beta 版本到 beta 5 了，还是没有修复，看来是没有人反馈？

**Comment by realJackWang** [comment]
我也是14.5beta5，无法使用自动复制功能。在edge里面直接打的url不行，用python requests也不行。

**Comment by hjt1997** [comment]
我也遇到了一样的问题，应该是IOS 14.4+才会碰到，粘贴后只有%clipboard%

**Comment by Finb** [comment]
> %clipboard%

这个是你发送时携带的copy参数值就是 %clipboard%， 你可以检查下你发送的请求，应该是错误的。

**Comment by hjt1997** [comment]
> > %clipboard%
> 
> 这个是你发送时携带的copy参数值就是 %clipboard%， 你可以检查下你发送的请求，应该是错误的。

没有设置其他参数值，具体操作是在office的PPT里复制文字发送给ipad，ipad收到通知消息后下拉复制，粘贴到goodnote5 时只有%clipboard%

**Comment by Finb** [comment]
> > > %clipboard%
> > 
> > 
> > 这个是你发送时携带的copy参数值就是 %clipboard%， 你可以检查下你发送的请求，应该是错误的。
> 
> 没有设置其他参数值，具体操作是在office的PPT里复制文字发送给ipad，ipad收到通知消息后下拉复制，粘贴到goodnote5 时只有%clipboard%
> 
> 另一个问题是在谷歌浏览器选择发送给设备，ipad只能收到前半段的内容，就像有字数限制一样。

我已经查明原因了，原因就是你使用的发送程序把%clipboard%当作copy参数值发送过来了，你应该修改你的发送程序，如果是第三方的需要去联系程序作者，我这边帮不了什么忙。

因APNS限制不能推送大段文本

**Comment by axelburks** [comment]
14.5 正式发布啦，还是有问题，是不是 Notification Service Extension 有 Bug？

**Comment by Finb** [comment]
@axelburks 应该不是bug，我debug发现有明确的错误提示。
之前iOS应用在后台就限制了不能读取剪切板了，这次权限收的更紧了

现在  Notification Service Extension 中运行代码完全不能访问剪切板，只写不读都不行了

**Comment by axelburks** [comment]
哦哦，好的

**Comment by h605290713** [comment]
这么好的功能 要凉？

**Comment by Today-to-Lsp** [comment]
ios

> @axelburks 应该不是bug，我debug发现有明确的错误提示。
> 之前iOS应用在后台就限制了不能读取剪切板了，这次权限收的更紧了
> 
> 现在 Notification Service Extension 中运行代码完全不能访问剪切板，只写不读都不行了

刚刚测试iphoneX iOS14.4.2 可以正常推送到剪切板，iphone12 pro max ios14.5，无法推送到剪切板

**Comment by Today-to-Lsp** [comment]
> @axelburks 应该不是bug，我debug发现有明确的错误提示。
> 之前iOS应用在后台就限制了不能读取剪切板了，这次权限收的更紧了
> 
> 现在 Notification Service Extension 中运行代码完全不能访问剪切板，只写不读都不行了


> ios
> 
> > @axelburks 应该不是bug，我debug发现有明确的错误提示。
> > 之前iOS应用在后台就限制了不能读取剪切板了，这次权限收的更紧了
> > 现在 Notification Service Extension 中运行代码完全不能访问剪切板，只写不读都不行了
> 
> 刚刚测试iphoneX iOS14.4.2 可以正常推送到剪切板，iphone12 pro max ios14.5，无法推送到剪切板

有没有其他的解决方法

**Comment by Finb** [comment]
@Today-to-Lsp 暂时没有
收到推送时下拉推送有个复制按钮，可以用那个替代一下
