### ISSUE TITLE
历史消息为空

### ISSUE THREAD

**Issue by ch634421335** [Finb/Bark#83]
1、设置中默认保存已打开  
2、本地测试加上isArchive=1
历史消息中均没有任何内容

**Comment by Finb** [comment]
重启下手机试试看，有些情况下 推送扩展 不能运行，重启下就好了。
另外你的系统版本号是多少呀？

**Comment by ch634421335** [comment]
> 重启下手机试试看，某些情况下按下扩展无法运行，重启下就好了。另外
> 你的系统版本号是多少呀？

ios14.3 重启解决了 感谢
