### ISSUE TITLE
能不能添加不对称加密功能呀

### ISSUE THREAD

**Issue by OvidioLee** [Finb/Bark#86]
能不能添加不对称加密功能呀

服务端直接密文传输，本地收到后再用秘钥解密

**Comment by Finb** [comment]
有什么特殊用处

如果是为了保护隐私，可以将服务端部署到自己服务器，传输走苹果的系统级加密，全程数据都不会泄露。

**Comment by OvidioLee** [comment]
没有什么特别的，仅仅是安全上的考量，毕竟是明文http传输

**Comment by Finb** [comment]
在自己的服务器部署后端，并使用https来传输推送内容，可以解决隐私安全问题。
