### ISSUE TITLE
如何防止被滥用呢？

### ISSUE THREAD

**Issue by zhi1ong** [Finb/Bark#89]
虽然 DeviceToken 不泄露不会导致别人给自己发消息，但是好像没办法保证自建的 bark-server 不会被别人扫到之后变成公用的服务

**Comment by Finb** [comment]
有个简单的，开启服务时设置 --user ， --password 参数，可以开启basic auth

**Comment by zhi1ong** [comment]
@Finb 一些三方应用支持 Bark 比较简单，不能设置 auth。。。 拼接到 url 中么
