### ISSUE TITLE
能不能提供重置Key功能？

### ISSUE THREAD

**Issue by andrychen** [Finb/Bark#9]
如果不小心泄露了注册设备时生成的Key值，那么别人就可以随意骚扰此Key对应的设备了（推送骚扰通知），希望能提供更改或重置新的Key值功能，谢谢。
补充：鉴于容易造成泄密骚扰，希望能为App加入启动密码功能。在多人共享的iPad上安装使用时特别需要。

**Comment by Finb** [comment]
线上的版本还不能重置key，如果需要重置可以重装App，能起到重置的效果。

多人共享的设备上还请谨慎使用，发过来的推送可是直接显示在通知中心的喔~ 
这个App大部分情况下也只在通知中心操作，不打开App

这个App是随身携带的轻量实时通知提醒应用，比较适合iPhone。 多人使用不随身携带的iPad我觉得不是很合适

**Comment by wahao** [comment]
小程序助手  已经支持生成临时链接        可以随时禁用、删除临时链接    应该可以满足你的需求

入口： 我的 > 实验性功能 > 临时链接 

[Bark-MP-helper](https://github.com/wahao/Bark-MP-helper)


![](https://mmbiz.qpic.cn/mmbiz_jpg/icWtmsIaSA69CyHTsibIXzplqso95e8IknUAnEC4JAYX8STEVrZAPCTBLeMjibuvu23XJsa1WicKaeEOh5GPlY5RUQ/0?wx_fmt=jpeg)



![演示](https://raw.githubusercontent.com/wahao/Bark-MP-helper/master/images/WechatIMG1136.jpeg)

**Comment by Finb** [comment]
#65
